create unique index if not exists character_inventory_character_item
  on public.character_inventory (character_id, item_name);

create table if not exists public.items (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  is_limited boolean not null default false,
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  low_stock_threshold integer not null default 5 check (low_stock_threshold >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inventory_transactions (
  id bigint generated by default as identity primary key,
  item_id bigint not null references public.items(id) on delete restrict,
  character_id integer references public.characters(id) on delete set null,
  quantity_change integer not null,
  transaction_type text not null
    check (transaction_type in ('initial', 'restock', 'adjustment', 'grant', 'revoke', 'use')),
  note text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists inventory_transactions_item_created_at
  on public.inventory_transactions (item_id, created_at desc);

insert into public.items (name, is_limited, stock_quantity)
select distinct trim(item_name), false, 0
from public.character_inventory
where nullif(trim(item_name), '') is not null
on conflict (name) do nothing;

alter table public.items enable row level security;
alter table public.inventory_transactions enable row level security;

create policy "Staff can view item catalog"
  on public.items for select
  to authenticated
  using (public.is_active_staff());

create policy "Staff can create catalog items"
  on public.items for insert
  to authenticated
  with check (public.is_active_staff());

create policy "Staff can update item metadata"
  on public.items for update
  to authenticated
  using (public.is_active_staff())
  with check (public.is_active_staff());

create policy "Staff can view inventory transactions"
  on public.inventory_transactions for select
  to authenticated
  using (public.is_active_staff());

create or replace function public.adjust_item_stock(
  p_item_id bigint,
  p_quantity_change integer,
  p_note text default null
)
returns public.items
language plpgsql
security definer
set search_path = public
as $$
declare
  target_item public.items;
  next_quantity integer;
begin
  if not public.is_active_staff() then
    raise exception 'Staff access required';
  end if;

  if p_quantity_change = 0 then
    raise exception 'Quantity change must not be zero';
  end if;

  select * into target_item
  from public.items
  where id = p_item_id
  for update;

  if not found then
    raise exception 'Item not found';
  end if;

  if not target_item.is_limited then
    raise exception 'Unlimited items do not use stock quantity';
  end if;

  next_quantity := target_item.stock_quantity + p_quantity_change;
  if next_quantity < 0 then
    raise exception 'Insufficient stock';
  end if;

  update public.items
  set stock_quantity = next_quantity, updated_at = now()
  where id = p_item_id
  returning * into target_item;

  insert into public.inventory_transactions (
    item_id,
    quantity_change,
    transaction_type,
    note,
    created_by
  )
  values (
    p_item_id,
    p_quantity_change,
    case when p_quantity_change > 0 then 'restock' else 'adjustment' end,
    nullif(p_note, ''),
    auth.uid()
  );

  return target_item;
end;
$$;

create or replace function public.grant_catalog_item(
  p_item_id bigint,
  p_character_id integer,
  p_quantity integer,
  p_note text default null
)
returns public.items
language plpgsql
security definer
set search_path = public
as $$
declare
  target_item public.items;
begin
  if not public.is_active_staff() then
    raise exception 'Staff access required';
  end if;

  if p_quantity <= 0 then
    raise exception 'Quantity must be greater than zero';
  end if;

  select * into target_item
  from public.items
  where id = p_item_id and active
  for update;

  if not found then
    raise exception 'Active item not found';
  end if;

  if target_item.is_limited then
    if target_item.stock_quantity < p_quantity then
      raise exception 'Insufficient stock';
    end if;

    update public.items
    set stock_quantity = stock_quantity - p_quantity, updated_at = now()
    where id = p_item_id
    returning * into target_item;
  end if;

  insert into public.character_inventory (character_id, item_name, quantity)
  values (p_character_id, target_item.name, p_quantity)
  on conflict (character_id, item_name)
  do update set quantity = public.character_inventory.quantity + excluded.quantity;

  insert into public.inventory_transactions (
    item_id,
    character_id,
    quantity_change,
    transaction_type,
    note,
    created_by
  )
  values (
    p_item_id,
    p_character_id,
    -p_quantity,
    'grant',
    nullif(p_note, ''),
    auth.uid()
  );

  return target_item;
end;
$$;

revoke all on function public.adjust_item_stock(bigint, integer, text) from public;
revoke all on function public.grant_catalog_item(bigint, integer, integer, text) from public;
grant execute on function public.adjust_item_stock(bigint, integer, text) to authenticated;
grant execute on function public.grant_catalog_item(bigint, integer, integer, text) to authenticated;
