alter table public.items
  add column if not exists use_category text not null default 'general',
  add column if not exists default_channel text,
  add column if not exists requires_target boolean not null default false,
  add column if not exists requires_roll boolean not null default false,
  add column if not exists action_template jsonb not null default '[]'::jsonb;

create table if not exists public.item_use_requests (
  id bigint generated by default as identity primary key,
  requester_character_id integer not null references public.characters(id) on delete restrict,
  target_character_id integer references public.characters(id) on delete set null,
  item_id bigint not null references public.items(id) on delete restrict,
  quantity integer not null default 1 check (quantity > 0),
  request_type text not null default 'self'
    check (request_type in ('self', 'target', 'secret_plan', 'shared_plot', 'unlock', 'defense')),
  actor_name text,
  use_channel text,
  desired_effect text not null,
  details text,
  role_url text,
  secrecy_level text not null default 'normal'
    check (secrecy_level in ('normal', 'staff_only', 'anonymous')),
  status text not null default 'submitted'
    check (status in (
      'submitted', 'revision', 'approved', 'action_pending',
      'awaiting_player', 'completed', 'rejected', 'cancelled'
    )),
  item_reserved boolean not null default false,
  staff_note text,
  requested_by uuid references auth.users(id) on delete set null,
  reviewed_by uuid references auth.users(id) on delete set null,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.item_request_tasks (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.item_use_requests(id) on delete cascade,
  label text not null,
  task_type text not null default 'staff_action',
  status text not null default 'pending'
    check (status in ('pending', 'done', 'skipped')),
  sort_order integer not null default 0,
  completed_by uuid references auth.users(id) on delete set null,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists item_use_requests_status_submitted
  on public.item_use_requests (status, submitted_at desc);

create index if not exists item_request_tasks_request_sort
  on public.item_request_tasks (request_id, sort_order, id);

alter table public.item_use_requests enable row level security;
alter table public.item_request_tasks enable row level security;

create policy "Staff can view item use requests"
  on public.item_use_requests for select
  to authenticated
  using (public.is_active_staff());

create policy "Staff can create item use requests"
  on public.item_use_requests for insert
  to authenticated
  with check (public.is_active_staff());

create policy "Staff can update item use requests"
  on public.item_use_requests for update
  to authenticated
  using (public.is_active_staff())
  with check (public.is_active_staff());

create policy "Staff can view item request tasks"
  on public.item_request_tasks for select
  to authenticated
  using (public.is_active_staff());

create policy "Staff can create item request tasks"
  on public.item_request_tasks for insert
  to authenticated
  with check (public.is_active_staff());

create policy "Staff can update item request tasks"
  on public.item_request_tasks for update
  to authenticated
  using (public.is_active_staff())
  with check (public.is_active_staff());

create or replace function public.create_staff_item_use_request(
  p_requester_character_id integer,
  p_item_id bigint,
  p_quantity integer,
  p_request_type text,
  p_target_character_id integer,
  p_actor_name text,
  p_use_channel text,
  p_desired_effect text,
  p_details text,
  p_role_url text,
  p_secrecy_level text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  target_item public.items;
  inventory_row public.character_inventory;
  request_id bigint;
  task_labels jsonb;
  task_label jsonb;
  task_order integer := 10;
begin
  if not public.is_active_staff() then
    raise exception 'Staff access required';
  end if;

  if p_quantity <= 0 then
    raise exception 'Quantity must be greater than zero';
  end if;

  select * into target_item
  from public.items
  where id = p_item_id and active;

  if not found then
    raise exception 'Active item not found';
  end if;

  select * into inventory_row
  from public.character_inventory
  where character_id = p_requester_character_id
    and item_name = target_item.name
  for update;

  if not found or inventory_row.quantity < p_quantity then
    raise exception 'Character does not have enough of this item';
  end if;

  update public.character_inventory
  set quantity = quantity - p_quantity
  where id = inventory_row.id;

  delete from public.character_inventory
  where id = inventory_row.id
    and quantity = 0;

  insert into public.item_use_requests (
    requester_character_id,
    target_character_id,
    item_id,
    quantity,
    request_type,
    actor_name,
    use_channel,
    desired_effect,
    details,
    role_url,
    secrecy_level,
    item_reserved,
    requested_by
  )
  values (
    p_requester_character_id,
    p_target_character_id,
    p_item_id,
    p_quantity,
    p_request_type,
    nullif(trim(p_actor_name), ''),
    nullif(trim(p_use_channel), ''),
    trim(p_desired_effect),
    nullif(trim(p_details), ''),
    nullif(trim(p_role_url), ''),
    p_secrecy_level,
    true,
    auth.uid()
  )
  returning id into request_id;

  insert into public.item_request_tasks (request_id, label, task_type, sort_order)
  values
    (request_id, 'ตรวจจำนวนและสิทธิ์ใช้ไอเท็ม', 'validation', 1),
    (request_id, 'ตรวจช่องทาง ผู้ลงมือ และผลกระทบ', 'validation', 2),
    (request_id, 'ดำเนินผล: ' || trim(p_desired_effect), 'staff_action', 50);

  task_labels := case
    when jsonb_typeof(target_item.action_template) = 'array'
      then target_item.action_template
    else '[]'::jsonb
  end;

  for task_label in select * from jsonb_array_elements(task_labels)
  loop
    insert into public.item_request_tasks (request_id, label, task_type, sort_order)
    values (
      request_id,
      coalesce(task_label->>'label', task_label #>> '{}'),
      coalesce(task_label->>'type', 'staff_action'),
      task_order
    );
    task_order := task_order + 1;
  end loop;

  if p_request_type = 'secret_plan' then
    insert into public.item_request_tasks (request_id, label, task_type, sort_order)
    values
      (request_id, 'ดำเนินแผนหรือปล่อยข่าวในช่องทางที่กำหนด', 'staff_action', 80),
      (request_id, 'บันทึกข่าวลือ ร่องรอย หรือผลสืบสวน', 'staff_action', 90);
  end if;

  if target_item.requires_roll then
    insert into public.item_request_tasks (request_id, label, task_type, sort_order)
    values (request_id, 'ส่งผลให้ผู้เกี่ยวข้องทอยและรอคำตอบ', 'player_action', 95);
  end if;

  insert into public.item_request_tasks (request_id, label, task_type, sort_order)
  values (request_id, 'แจ้งผลและปิดคำร้อง', 'staff_action', 100);

  return request_id;
end;
$$;

create or replace function public.set_item_request_task_status(
  p_task_id bigint,
  p_status text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_active_staff() then
    raise exception 'Staff access required';
  end if;

  if p_status not in ('pending', 'done', 'skipped') then
    raise exception 'Invalid task status';
  end if;

  update public.item_request_tasks
  set
    status = p_status,
    completed_by = case when p_status = 'pending' then null else auth.uid() end,
    completed_at = case when p_status = 'pending' then null else now() end
  where id = p_task_id;
end;
$$;

create or replace function public.review_item_use_request(
  p_request_id bigint,
  p_status text,
  p_staff_note text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  request_row public.item_use_requests;
  target_item public.items;
begin
  if not public.is_active_staff() then
    raise exception 'Staff access required';
  end if;

  if p_status not in (
    'revision', 'approved', 'action_pending', 'awaiting_player',
    'completed', 'rejected', 'cancelled'
  ) then
    raise exception 'Invalid request status';
  end if;

  select * into request_row
  from public.item_use_requests
  where id = p_request_id
  for update;

  if not found then
    raise exception 'Request not found';
  end if;

  select * into target_item from public.items where id = request_row.item_id;

  if p_status in ('rejected', 'cancelled') and request_row.item_reserved then
    insert into public.character_inventory (character_id, item_name, quantity)
    values (
      request_row.requester_character_id,
      target_item.name,
      request_row.quantity
    )
    on conflict (character_id, item_name)
    do update set quantity = public.character_inventory.quantity + excluded.quantity;

    request_row.item_reserved := false;
  end if;

  if p_status = 'completed' and request_row.item_reserved then
    insert into public.inventory_transactions (
      item_id,
      character_id,
      quantity_change,
      transaction_type,
      note,
      created_by
    )
    values (
      request_row.item_id,
      request_row.requester_character_id,
      -request_row.quantity,
      'use',
      coalesce(nullif(trim(p_staff_note), ''), request_row.desired_effect),
      auth.uid()
    );

    request_row.item_reserved := false;
  end if;

  update public.item_use_requests
  set
    status = p_status,
    item_reserved = request_row.item_reserved,
    staff_note = nullif(trim(p_staff_note), ''),
    reviewed_by = auth.uid(),
    updated_at = now(),
    completed_at = case when p_status = 'completed' then now() else null end
  where id = p_request_id;
end;
$$;

revoke all on function public.create_staff_item_use_request(
  integer, bigint, integer, text, integer, text, text, text, text, text, text
) from public;
revoke all on function public.set_item_request_task_status(bigint, text) from public;
revoke all on function public.review_item_use_request(bigint, text, text) from public;

grant execute on function public.create_staff_item_use_request(
  integer, bigint, integer, text, integer, text, text, text, text, text, text
) to authenticated;
grant execute on function public.set_item_request_task_status(bigint, text) to authenticated;
grant execute on function public.review_item_use_request(bigint, text, text) to authenticated;
