-- Run after 20260815002000_auto_deliver_legal_purchases.sql.
-- Restricted acquisition access belongs to an NPC, not to each item.

begin;

create table if not exists public.character_acquisition_channel_unlocks (
  id bigint generated by default as identity primary key,
  character_id integer not null references public.characters(id) on delete cascade,
  acquisition_channel_id bigint not null references public.acquisition_channels(id) on delete cascade,
  source text,
  note text,
  unlocked_by uuid references auth.users(id) on delete set null,
  unlocked_at timestamptz not null default now(),
  unique (character_id, acquisition_channel_id)
);

create index if not exists character_channel_unlocks_character
  on public.character_acquisition_channel_unlocks (character_id, acquisition_channel_id);

alter table public.character_acquisition_channel_unlocks enable row level security;

drop policy if exists "Staff can manage NPC acquaintance unlocks"
  on public.character_acquisition_channel_unlocks;
create policy "Staff can manage NPC acquaintance unlocks"
  on public.character_acquisition_channel_unlocks for all
  to authenticated
  using (public.is_active_staff())
  with check (public.is_active_staff());

-- Preserve access already granted through the former per-item system.
insert into public.character_acquisition_channel_unlocks (
  character_id,
  acquisition_channel_id,
  source,
  note,
  unlocked_by,
  unlocked_at
)
select distinct on (old_unlock.character_id, item.acquisition_channel_id)
  old_unlock.character_id,
  item.acquisition_channel_id,
  old_unlock.source,
  old_unlock.note,
  old_unlock.unlocked_by,
  old_unlock.unlocked_at
from public.character_catalog_unlocks old_unlock
join public.items item on item.id = old_unlock.item_id
where item.acquisition_channel_id is not null
order by old_unlock.character_id, item.acquisition_channel_id, old_unlock.unlocked_at
on conflict (character_id, acquisition_channel_id) do nothing;

create or replace function public.unlock_character_acquisition_channel(
  p_character_id integer,
  p_acquisition_channel_id bigint,
  p_source text default null,
  p_note text default null
)
returns public.character_acquisition_channel_unlocks
language plpgsql
security definer
set search_path = public
as $$
declare
  unlock_row public.character_acquisition_channel_unlocks;
begin
  if not public.is_active_staff() then raise exception 'Staff access required'; end if;
  if not exists (
    select 1 from public.acquisition_channels
    where id = p_acquisition_channel_id and active
  ) then
    raise exception 'NPC acquisition channel not found';
  end if;

  insert into public.character_acquisition_channel_unlocks (
    character_id, acquisition_channel_id, source, note, unlocked_by
  ) values (
    p_character_id, p_acquisition_channel_id, nullif(btrim(p_source), ''),
    nullif(btrim(p_note), ''), auth.uid()
  )
  on conflict (character_id, acquisition_channel_id) do update set
    source = excluded.source,
    note = excluded.note,
    unlocked_by = auth.uid(),
    unlocked_at = now()
  returning * into unlock_row;

  return unlock_row;
end;
$$;

drop function if exists public.get_player_item_catalog(integer);
create function public.get_player_item_catalog(
  p_character_id integer
)
returns table (
  id bigint,
  name text,
  description text,
  cost integer,
  price_currency text,
  acquisition_type text,
  catalog_visibility text,
  acquisition_requires_roll boolean,
  minimum_favor integer,
  fulfillment_days_min integer,
  fulfillment_days_max integer,
  is_limited boolean,
  stock_quantity integer,
  use_category text,
  acquisition_channel_id bigint,
  unlocked boolean,
  can_request boolean,
  action_label text,
  acquisition_channel_name text,
  acquisition_channel_role text,
  acquisition_channel_access_reason text,
  acquisition_channel_motivation text,
  acquisition_unlock_method text,
  acquisition_risk_summary text,
  acquisition_risk_level integer
)
language sql
security definer
set search_path = public
stable
as $$
  with character_row as (
    select
      character.id,
      character.position,
      coalesce(character.favor, 0) as favor,
      coalesce(privilege.can_command_external_purchase, false) as can_command
    from public.characters character
    left join public.character_position_acquisition_privileges privilege
      on privilege.position = character.position
    where character.id = p_character_id
  ), catalog as (
    select
      item.*,
      character_row.favor as character_favor,
      character_row.can_command,
      channel.npc_name,
      channel.npc_role,
      channel.access_reason,
      channel.motivation,
      channel.unlock_method,
      channel.risk_summary,
      case
        when item.acquisition_type = 'restricted'
          then channel_unlock.id is not null
        when item.catalog_visibility = 'locked'
          then item_unlock.id is not null
        else true
      end as access_unlocked
    from public.items item
    cross join character_row
    left join public.character_acquisition_channel_unlocks channel_unlock
      on channel_unlock.character_id = character_row.id
      and channel_unlock.acquisition_channel_id = item.acquisition_channel_id
    left join public.character_catalog_unlocks item_unlock
      on item_unlock.character_id = character_row.id
      and item_unlock.item_id = item.id
    left join public.acquisition_channels channel
      on channel.id = item.acquisition_channel_id and channel.active
    where item.active
      and item.catalog_visibility <> 'staff_only'
      and (
        item.shop_available
        or item.acquisition_type = 'story_only'
        or item.catalog_visibility = 'locked'
      )
  )
  select
    catalog.id,
    case when not catalog.access_unlocked
      then 'ผู้ติดต่อที่ยังไม่รู้จัก' else catalog.name end,
    case when not catalog.access_unlocked
      then 'ต้องพบเบาะแสหรือสร้างความไว้วางใจกับ NPC ก่อนจึงจะเห็นสิ่งที่เขาจัดหาได้'
      else catalog.description end,
    catalog.cost,
    catalog.price_currency,
    catalog.acquisition_type,
    catalog.catalog_visibility,
    catalog.acquisition_requires_roll,
    catalog.minimum_favor,
    case
      when catalog.acquisition_type = 'external_legal' and catalog.can_command
        then greatest(0, catalog.fulfillment_days_min - 1)
      else catalog.fulfillment_days_min
    end,
    case
      when catalog.acquisition_type = 'external_legal' and catalog.can_command
        then greatest(
          greatest(0, catalog.fulfillment_days_min - 1),
          catalog.fulfillment_days_max - 2
        )
      else catalog.fulfillment_days_max
    end,
    catalog.is_limited,
    catalog.stock_quantity,
    catalog.use_category,
    catalog.acquisition_channel_id,
    catalog.access_unlocked,
    case
      when catalog.acquisition_type = 'story_only' then false
      when not catalog.access_unlocked then false
      when catalog.character_favor < catalog.minimum_favor then false
      when catalog.is_limited and catalog.stock_quantity <= 0 then false
      else true
    end,
    case
      when catalog.acquisition_type = 'story_only' then 'ได้รับจากการสำรวจเท่านั้น'
      when not catalog.access_unlocked then 'ยังไม่รู้จัก NPC'
      when catalog.character_favor < catalog.minimum_favor then 'โปรดปรานยังไม่ถึงเกณฑ์'
      when catalog.acquisition_type = 'palace_stock' then 'เบิกจากคลัง'
      when catalog.acquisition_type = 'external_legal' and catalog.can_command
        then 'ออกคำสั่งให้จัดซื้อ'
      when catalog.acquisition_type = 'external_legal' then 'ส่งคำขอจัดซื้อ'
      when catalog.acquisition_type = 'restricted' then 'เจรจาซื้อ'
      else 'ไม่สามารถขอได้'
    end,
    case when catalog.access_unlocked then catalog.npc_name else null end,
    case when catalog.access_unlocked then catalog.npc_role else null end,
    case when catalog.access_unlocked then catalog.access_reason else null end,
    case when catalog.access_unlocked then catalog.motivation else null end,
    case when catalog.access_unlocked then catalog.unlock_method else null end,
    case when catalog.access_unlocked then catalog.risk_summary else null end,
    catalog.acquisition_risk_level
  from catalog
  order by
    case catalog.acquisition_type
      when 'palace_stock' then 1
      when 'external_legal' then 2
      when 'restricted' then 3
      else 4
    end,
    catalog.npc_name nulls last,
    catalog.name;
$$;

create or replace function public.submit_item_acquisition_request(
  p_character_id integer,
  p_item_id bigint,
  p_quantity integer default 1,
  p_player_note text default null
)
returns public.item_acquisition_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  character_row public.characters;
  item_row public.items;
  channel_unlock_row public.character_acquisition_channel_unlocks;
  item_unlock_row public.character_catalog_unlocks;
  request_row public.item_acquisition_requests;
  route_value text;
  should_auto_fulfill boolean;
  should_schedule_delivery boolean;
  can_command boolean := false;
  total_cost integer;
  delivery_days_min integer;
  delivery_days_max integer;
  delivery_days integer;
begin
  if p_quantity <= 0 then raise exception 'Quantity must be positive'; end if;

  select * into character_row from public.characters
  where id = p_character_id for update;
  if not found then raise exception 'Character not found'; end if;

  select * into item_row from public.items
  where id = p_item_id and active for update;
  if not found then raise exception 'Catalog item not found'; end if;

  if item_row.acquisition_type = 'story_only' then
    raise exception 'Story items cannot be requested from the catalog';
  end if;
  if item_row.catalog_visibility = 'staff_only' then
    raise exception 'Catalog item is not available';
  end if;
  if item_row.acquisition_type = 'restricted' then
    if item_row.acquisition_channel_id is null then
      raise exception 'NPC acquisition channel is not configured';
    end if;
    select * into channel_unlock_row
    from public.character_acquisition_channel_unlocks
    where character_id = p_character_id
      and acquisition_channel_id = item_row.acquisition_channel_id;
    if not found then raise exception 'NPC acquaintance is locked'; end if;
  elsif item_row.catalog_visibility = 'locked' then
    select * into item_unlock_row from public.character_catalog_unlocks
    where character_id = p_character_id and item_id = p_item_id;
    if not found then raise exception 'Acquisition channel is locked'; end if;
  end if;
  if coalesce(character_row.favor, 0) < item_row.minimum_favor then
    raise exception 'Insufficient Favor threshold';
  end if;
  if item_row.price_currency <> 'rp' then
    raise exception 'Catalog acquisition must use RP';
  end if;

  select exists (
    select 1
    from public.character_position_acquisition_privileges privilege
    where privilege.position = character_row.position
      and privilege.can_command_external_purchase
  ) into can_command;

  total_cost := item_row.cost * p_quantity;
  route_value := case
    when item_row.acquisition_type = 'palace_stock' then 'requisition'
    when item_row.acquisition_type = 'external_legal' and can_command then 'command'
    when item_row.acquisition_type = 'external_legal' then 'procurement'
    else 'restricted_contact'
  end;
  should_auto_fulfill := item_row.acquisition_type = 'palace_stock'
    and item_row.auto_fulfill and not item_row.acquisition_requires_roll;
  should_schedule_delivery := item_row.acquisition_type = 'external_legal'
    and not item_row.acquisition_requires_roll;

  if should_auto_fulfill or should_schedule_delivery then
    if coalesce(character_row.rp, 0) < total_cost then raise exception 'Insufficient RP'; end if;
    if item_row.is_limited and item_row.stock_quantity < p_quantity then
      raise exception 'Item is out of stock';
    end if;

    update public.characters set rp = coalesce(rp, 0) - total_cost
      where id = p_character_id;
    if item_row.is_limited then
      update public.items set stock_quantity = stock_quantity - p_quantity, updated_at = now()
      where id = p_item_id;
    end if;
  end if;

  if should_auto_fulfill then
    insert into public.character_inventory (character_id, item_name, quantity)
    values (p_character_id, item_row.name, p_quantity)
    on conflict (character_id, item_name)
    do update set quantity = public.character_inventory.quantity + excluded.quantity;

    insert into public.item_acquisition_requests (
      character_id, item_id, quantity, request_route, status, player_note,
      charged_currency, charged_amount, stock_reserved, item_granted,
      requested_by, completed_at, acquisition_channel_id, auto_delivery
    ) values (
      p_character_id, p_item_id, p_quantity, route_value, 'completed',
      nullif(btrim(p_player_note), ''), 'rp', total_cost,
      false, true, auth.uid(), now(),
      item_row.acquisition_channel_id, false
    ) returning * into request_row;

    insert into public.inventory_transactions (
      item_id, character_id, quantity_change, transaction_type, note
    ) values (
      p_item_id, p_character_id, -p_quantity, 'purchase',
      'เบิกจากคลังหลวง · ' || total_cost || ' RP'
    );
  elsif should_schedule_delivery then
    delivery_days_min := case when can_command
      then greatest(0, item_row.fulfillment_days_min - 1)
      else item_row.fulfillment_days_min end;
    delivery_days_max := case when can_command
      then greatest(delivery_days_min, item_row.fulfillment_days_max - 2)
      else item_row.fulfillment_days_max end;
    delivery_days := delivery_days_min + floor(
      random() * (delivery_days_max - delivery_days_min + 1)
    )::integer;

    insert into public.item_acquisition_requests (
      character_id, item_id, quantity, request_route, status, player_note,
      charged_currency, charged_amount, stock_reserved, item_granted,
      requested_by, acquisition_channel_id, auto_delivery, available_at
    ) values (
      p_character_id, p_item_id, p_quantity, route_value, 'procuring',
      nullif(btrim(p_player_note), ''), 'rp', total_cost,
      item_row.is_limited, false, auth.uid(), item_row.acquisition_channel_id,
      true, now() + make_interval(days => delivery_days)
    ) returning * into request_row;
  else
    insert into public.item_acquisition_requests (
      character_id, item_id, quantity, request_route, status, player_note,
      success_chance_percent, requested_by, acquisition_channel_id, roll_phase,
      auto_delivery
    ) values (
      p_character_id, p_item_id, p_quantity, route_value, 'submitted',
      nullif(btrim(p_player_note), ''),
      case when item_row.acquisition_requires_roll
        then item_row.acquisition_success_percent else null end,
      auth.uid(), item_row.acquisition_channel_id,
      case when item_row.acquisition_requires_roll
        then 'contact_and_smuggling' else null end,
      false
    ) returning * into request_row;
  end if;

  insert into public.character_history (character_id, action, value, type)
  values (
    p_character_id,
    case
      when should_auto_fulfill then 'เบิกไอเท็ม'
      when should_schedule_delivery then 'สั่งจัดหาไอเท็ม'
      when item_row.acquisition_type = 'restricted' then 'เจรจาซื้อกับ NPC'
      else 'ส่งคำร้องจัดหาไอเท็ม'
    end,
    item_row.name || ' ×' || p_quantity,
    'item_acquisition'
  );
  return request_row;
end;
$$;

revoke all on function public.unlock_character_acquisition_channel(integer, bigint, text, text) from public;
revoke all on function public.get_player_item_catalog(integer) from public;
revoke all on function public.submit_item_acquisition_request(integer, bigint, integer, text) from public;

grant execute on function public.unlock_character_acquisition_channel(integer, bigint, text, text) to authenticated;
grant execute on function public.get_player_item_catalog(integer) to anon, authenticated;
grant execute on function public.submit_item_acquisition_request(integer, bigint, integer, text) to anon, authenticated;

commit;
