create table if not exists public.exploration_locations (
  id bigint generated by default as identity primary key,
  code text not null unique,
  zone_number integer not null unique check (zone_number between 1 and 99),
  name text not null,
  short_name text not null,
  category text not null,
  summary text,
  tags text[] not null default '{}',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.exploration_locations enable row level security;

drop policy if exists "Anyone can view active exploration locations"
  on public.exploration_locations;
create policy "Anyone can view active exploration locations"
  on public.exploration_locations for select
  to anon, authenticated
  using (active);

drop policy if exists "Staff can manage exploration locations"
  on public.exploration_locations;
create policy "Staff can manage exploration locations"
  on public.exploration_locations for all
  to authenticated
  using (public.is_active_staff())
  with check (public.is_active_staff());

grant select on public.exploration_locations to anon, authenticated;
grant insert, update, delete on public.exploration_locations to authenticated;
grant usage, select on sequence public.exploration_locations_id_seq
  to authenticated;

insert into public.exploration_locations (
  code, zone_number, name, short_name, category, summary, tags, sort_order
)
values
  ('main_gate', 1, 'เขตประตูใหญ่ คูน้ำ และลานพิธีหน้าวัง', 'ประตูใหญ่วังหลวง', 'วังหน้า', 'จุดเข้าออกหลัก ลานพิธี และแนวรักษาการณ์หน้าวัง', array['ประตู', 'การเดินทาง', 'บุคคลเข้าออก', 'ข่าว', 'ความปลอดภัย'], 1),
  ('court_government', 2, 'เขตท้องพระโรงและราชการ', 'ท้องพระโรงและราชการ', 'วังหน้า', 'ศูนย์กลางพิธีราชสำนัก งานราชการ และการรับรองราชทูต', array['ราชการ', 'พิธีการ', 'การเมือง', 'การทูต', 'ข่าว'], 2),
  ('archives_treasury', 3, 'ห้องฎีกา หอจดหมายเหตุ และหอพระคลัง', 'หอจดหมายเหตุและพระคลัง', 'เขตขุนนาง', 'พื้นที่เอกสารลับ ฎีกา ทรัพย์สิน และบัญชีสำคัญ', array['เอกสาร', 'ข่าว', 'ความลับ', 'ทรัพย์สิน', 'การเงิน'], 3),
  ('military_quarter', 4, 'เขตทหาร ค่ายพัก คลังอาวุธ และคอกม้า', 'เขตทหารและคอกม้า', 'เขตทหาร', 'พื้นที่กองกำลัง อาวุธ การฝึก และการเดินทางด้วยม้า', array['ทหาร', 'อาวุธ', 'การเมือง', 'ติดตามคน', 'ความปลอดภัย'], 4),
  ('emperor_office', 5, 'เขตพระตำหนักทรงงานของฮ่องเต้', 'พระตำหนักทรงงาน', 'เขตฮ่องเต้', 'พื้นที่ว่าราชการภายใน หอหนังสือ และพระบัญชา', array['ราชการ', 'การเมือง', 'เอกสาร', 'ข่าว', 'ความลับ'], 5),
  ('emperor_bedchamber', 6, 'พระตำหนักบรรทมฮ่องเต้', 'พระตำหนักบรรทม', 'เขตฮ่องเต้', 'เขตส่วนพระองค์ที่มีการรักษาความปลอดภัยสูงสุด', array['ข่าววังหลัง', 'ติดตามคน', 'ความลับ', 'ความปลอดภัย'], 6),
  ('front_rear_gate', 7, 'ประตูเชื่อมวังหน้า–วังหลัง', 'ประตูวังหน้า–วังหลัง', 'วังหลังส่วนกลาง', 'จุดตรวจป้ายและเส้นทางเชื่อมระหว่างเขตราชการกับฝ่ายใน', array['ประตู', 'การเดินทาง', 'บุคคลเข้าออก', 'ข่าววังหลัง', 'ความปลอดภัย'], 7),
  ('rear_gardens', 8, 'เขตทางเดินและสวนส่วนกลางวังหลัง', 'สวนกลางวังหลัง', 'วังหลังส่วนกลาง', 'สวนหลวง ศาลากลางน้ำ และทางเดินระหว่างตำหนัก', array['สวน', 'สมุนไพร', 'ข่าววังหลัง', 'ข่าวพระสนม', 'ติดตามคน'], 8),
  ('dowager_palace', 9, 'ตำหนักไทเฮา', 'ตำหนักไทเฮา', 'ตำหนักไทเฮา/ฮองเฮา', 'เขตตำหนักและลานรับรองของไทเฮา', array['ข่าววังหลัง', 'การเมือง', 'ข่าวพระสนม', 'พิธีการ'], 9),
  ('empress_palace', 10, 'ตำหนักกลางหลวงของฮองเฮา', 'ตำหนักฮองเฮา', 'ตำหนักไทเฮา/ฮองเฮา', 'ศูนย์กลางการปกครองฝ่ายในและงานของฮองเฮา', array['ข่าววังหลัง', 'การเมือง', 'ข่าวพระสนม', 'พิธีการ'], 10),
  ('first_rank_consorts', 11, 'ตำหนักพระสนมขั้น 1 — เฟยทั้งสี่', 'ตำหนักเฟยทั้งสี่', 'ตำหนักพระสนม', 'ตำหนักของพระสนมขั้นหนึ่งและข้ารับใช้ในสังกัด', array['ข่าววังหลัง', 'ข่าวพระสนม', 'ติดตามคน', 'ความลับ'], 11),
  ('second_rank_consorts', 12, 'ตำหนักพระสนมขั้น 2 — จิ่วผิน', 'ตำหนักจิ่วผิน', 'ตำหนักพระสนม', 'ตำหนักของพระสนมขั้นสองและลานรับรอง', array['ข่าววังหลัง', 'ข่าวพระสนม', 'ติดตามคน', 'ความลับ'], 12),
  ('mid_rank_consorts', 13, 'ตำหนักรวมสนมขั้น 3–5', 'ตำหนักรวมขั้น 3–5', 'ตำหนักพระสนม', 'ลานรวมและเรือนพักแยกของเจี๋ยอวี๋ เหม่ยเหริน และไฉเหริน', array['ข่าววังหลัง', 'ข่าวพระสนม', 'ติดตามคน', 'ข่าว'], 13),
  ('low_rank_consorts', 14, 'เขตสนมขั้นต่ำ 6–8', 'เขตสนมขั้นต่ำ', 'ตำหนักพระสนม', 'เขตพักของเป่าหลิน ยวี่หนวี่ และไฉหนวี่', array['ข่าววังหลัง', 'ข่าวพระสนม', 'ติดตามคน', 'ข่าว'], 14),
  ('imperial_kitchen', 15, 'ฝ่ายห้องเครื่อง ครัว และคลังเสบียง', 'ห้องเครื่องและคลังเสบียง', 'ครัว–คลัง–ซักล้าง', 'พื้นที่ประกอบอาหาร รับส่งสำรับ และจัดเก็บเสบียง', array['อาหาร', 'ข่าวห้องเครื่อง', 'วัตถุดิบ', 'การค้า', 'ข่าว'], 15),
  ('laundry_wardrobe', 16, 'โรงซัก โรงย้อม งานเย็บปัก และคลังเครื่องแต่งกาย', 'โรงซักและคลังเครื่องแต่งกาย', 'ครัว–คลัง–ซักล้าง', 'พื้นที่ซักย้อม เย็บปัก และดูแลเครื่องแต่งกายฝ่ายใน', array['เครื่องแต่งกาย', 'งานฝีมือ', 'ข่าววังหลัง', 'ข่าว', 'วัตถุดิบ'], 16),
  ('medical_bureau', 17, 'กองโอสถ ห้องปรุงยา และสวนสมุนไพร', 'กองโอสถและสวนสมุนไพร', 'กองโอสถ', 'พื้นที่รักษา ปรุงยา จัดเก็บยา และปลูกสมุนไพร', array['สมุนไพร', 'การแพทย์', 'ยา', 'สวน', 'ข่าว'], 17),
  ('crescent_temple', 18, 'วัดจันทร์เสี้ยวและศาลบรรพชน', 'วัดและศาลบรรพชน', 'เขตพิธีกรรม', 'พื้นที่ประกอบพิธี เก็บคัมภีร์ และสักการะบรรพชน', array['พิธีการ', 'ศาสนา', 'คัมภีร์', 'ความลับ', 'ข่าว'], 18),
  ('servant_quarters', 19, 'เรือนพักขันทีและเรือนนางกำนัล', 'เรือนพักข้าราชบริพาร', 'เขตที่พักฝ่ายใน', 'เรือนพักของขันทีและนางกำนัลแต่ละฝ่าย', array['ข่าววังหลัง', 'ข่าว', 'ติดตามคน', 'บุคคล', 'ความลับ'], 19),
  ('service_gate', 20, 'ประตูบริการ ประตูหลัง และทางส่งเสบียง', 'ประตูบริการและทางเสบียง', 'เขตบริการ', 'เส้นทางรับส่งของ รถเสบียง และการเข้าออกด้านหลังวัง', array['การเดินทาง', 'การค้า', 'วัตถุดิบ', 'บุคคลเข้าออก', 'ข่าว'], 20)
on conflict (code) do update
set
  zone_number = excluded.zone_number,
  name = excluded.name,
  short_name = excluded.short_name,
  category = excluded.category,
  summary = excluded.summary,
  tags = excluded.tags,
  sort_order = excluded.sort_order,
  updated_at = now();

create table if not exists public.follower_talents (
  id bigint generated by default as identity primary key,
  follower_id bigint not null references public.follower_master(id) on delete cascade,
  talent_key text not null,
  label text not null,
  modifier_percent integer not null check (modifier_percent between -100 and 100),
  created_at timestamptz not null default now(),
  unique (follower_id, talent_key)
);

create index if not exists follower_talents_follower
  on public.follower_talents (follower_id);

alter table public.follower_talents enable row level security;

drop policy if exists "Anyone can view follower talents"
  on public.follower_talents;
create policy "Anyone can view follower talents"
  on public.follower_talents for select
  to anon, authenticated
  using (true);

drop policy if exists "Staff can manage follower talents"
  on public.follower_talents;
create policy "Staff can manage follower talents"
  on public.follower_talents for all
  to authenticated
  using (public.is_active_staff())
  with check (public.is_active_staff());

grant select on public.follower_talents to anon, authenticated;
grant insert, update, delete on public.follower_talents to authenticated;
grant usage, select on sequence public.follower_talents_id_seq
  to authenticated;

alter table public.follower_explorations
  add column if not exists location_id bigint
    references public.exploration_locations(id) on delete restrict,
  add column if not exists suitability_percent integer not null default 0;

create index if not exists follower_explorations_location
  on public.follower_explorations (location_id);

update public.follower_explorations mission
set location_id = location.id
from public.exploration_locations location
where mission.location_id is null
  and (
    mission.destination = location.name
    or mission.destination = location.short_name
  );

drop function if exists public.start_follower_exploration(
  integer, bigint, text, text
);

create or replace function public.start_follower_exploration(
  p_character_id integer,
  p_follower_id bigint,
  p_location_id bigint,
  p_objective text default null
)
returns public.follower_explorations
language plpgsql
security definer
set search_path = public
as $$
declare
  follower_row public.follower_master;
  location_row public.exploration_locations;
  mission_row public.follower_explorations;
  mission_count integer;
  suitability integer;
begin
  select * into follower_row
  from public.follower_master
  where id = p_follower_id
  for update;

  if not found
    or follower_row.owner_character_id is distinct from p_character_id then
    raise exception 'Follower does not belong to this character';
  end if;

  if btrim(coalesce(follower_row.status, ''), E' \n\r\t') <> 'idle' then
    raise exception 'Follower is already on a mission';
  end if;

  select * into location_row
  from public.exploration_locations
  where id = p_location_id and active;

  if not found then
    raise exception 'Exploration location is not available';
  end if;

  select count(*) into mission_count
  from public.follower_explorations
  where follower_id = p_follower_id
    and started_at >= date_trunc('week', now())
    and status <> 'cancelled';

  if mission_count >= coalesce(follower_row.weekly_mission_limit, 1) then
    raise exception 'Follower weekly mission limit reached';
  end if;

  select coalesce(sum(talent.modifier_percent), 0)::integer
  into suitability
  from public.follower_talents talent
  where talent.follower_id = p_follower_id
    and talent.talent_key = any(location_row.tags);

  insert into public.follower_explorations (
    follower_id,
    character_id,
    location_id,
    destination,
    objective,
    suitability_percent
  )
  values (
    p_follower_id,
    p_character_id,
    location_row.id,
    location_row.name,
    nullif(trim(p_objective), ''),
    suitability
  )
  returning * into mission_row;

  update public.follower_master
  set status = 'exploring', updated_at = now()
  where id = p_follower_id;

  insert into public.character_history (
    character_id,
    action,
    value,
    type
  )
  values (
    p_character_id,
    'ส่งผู้ติดตามสำรวจ',
    follower_row.name || ' → ' || location_row.short_name,
    'follower_mission'
  );

  return mission_row;
end;
$$;

drop function if exists public.get_player_follower_explorations(integer);

create function public.get_player_follower_explorations(
  p_character_id integer
)
returns table (
  id bigint,
  follower_id bigint,
  location_id bigint,
  location_code text,
  location_category text,
  destination text,
  objective text,
  suitability_percent integer,
  status text,
  result_summary text,
  result_details text,
  reward_item_name text,
  reward_quantity integer,
  started_at timestamptz,
  completed_at timestamptz
)
language sql
security definer
set search_path = public
stable
as $$
  select
    mission.id,
    mission.follower_id,
    mission.location_id,
    location.code,
    location.category,
    mission.destination,
    mission.objective,
    mission.suitability_percent,
    mission.status,
    mission.result_summary,
    mission.result_details,
    reward.name,
    mission.reward_quantity,
    mission.started_at,
    mission.completed_at
  from public.follower_explorations mission
  left join public.exploration_locations location
    on location.id = mission.location_id
  left join public.items reward on reward.id = mission.reward_item_id
  where mission.character_id = p_character_id
  order by mission.started_at desc
  limit 30;
$$;

revoke all on function public.start_follower_exploration(
  integer, bigint, bigint, text
) from public;
revoke all on function public.get_player_follower_explorations(integer)
  from public;

grant execute on function public.start_follower_exploration(
  integer, bigint, bigint, text
) to anon, authenticated;
grant execute on function public.get_player_follower_explorations(integer)
  to anon, authenticated;
