-- Run after 20260814000000_add_item_acquisition_workflow.sql.
-- Completes position-based procurement, restricted acquisition lore/risk,
-- and database-backed RP/Favor reward guidance.

begin;

create table if not exists public.acquisition_channels (
  id bigint generated by default as identity primary key,
  code text not null unique,
  npc_name text not null,
  npc_role text not null,
  access_reason text not null,
  motivation text not null,
  hidden_secret text not null,
  unlock_method text not null,
  risk_summary text not null,
  risk_level integer not null default 3 check (risk_level between 1 and 5),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.acquisition_channels enable row level security;
drop policy if exists "Staff can manage acquisition channels"
  on public.acquisition_channels;
create policy "Staff can manage acquisition channels"
  on public.acquisition_channels for all
  to authenticated
  using (public.is_active_staff())
  with check (public.is_active_staff());

grant select, insert, update, delete on public.acquisition_channels to authenticated;
grant usage, select on sequence public.acquisition_channels_id_seq to authenticated;

insert into public.acquisition_channels (
  code, npc_name, npc_role, access_reason, motivation, hidden_secret,
  unlock_method, risk_summary, risk_level
) values (
  'luo-jing-supply-ledger',
  'หลัวจิ้ง',
  'เสมียนบัญชีรถส่งเสบียงประจำประตูฝ่ายใน',
  'ตรวจบัญชีรถส่งเสบียงและใบผ่านเข้าออก จึงซ่อนห่อของขนาดเล็กมากับของที่ได้รับอนุญาตได้',
  'ต้องการเงินชำระหนี้ครอบครัวและสะสมข้อมูลไว้ต่อรองเพื่อเอาตัวรอด',
  'เคยแก้บัญชีส่งของให้ผู้มีอำนาจในวัง หากบัญชีเก่าถูกพบจะเสียทั้งตำแหน่งและชีวิต',
  'ปลดล็อกจากเบาะแสเรื่องบัญชีส่งเสบียง ช่วยปิดร่องรอยให้เขา หรือได้รับการแนะนำจากผู้ติดต่อที่ไว้ใจได้',
  'หากล้มเหลวคำร้องจะถูกปิดและคืน RP แต่ช่องทางอาจถูกจับตาหรือเกิดเบาะแสให้ฝ่ายตรวจการตามต่อ',
  4
)
on conflict (code) do update set
  npc_name = excluded.npc_name,
  npc_role = excluded.npc_role,
  access_reason = excluded.access_reason,
  motivation = excluded.motivation,
  hidden_secret = excluded.hidden_secret,
  unlock_method = excluded.unlock_method,
  risk_summary = excluded.risk_summary,
  risk_level = excluded.risk_level,
  active = true,
  updated_at = now();

alter table public.items
  add column if not exists acquisition_channel_id bigint
    references public.acquisition_channels(id) on delete set null,
  add column if not exists acquisition_risk_level integer not null default 1,
  add column if not exists failure_consequence text,
  add column if not exists critical_failure_consequence text;

alter table public.items
  drop constraint if exists items_acquisition_risk_level_check,
  add constraint items_acquisition_risk_level_check
    check (acquisition_risk_level between 1 and 5);

create table if not exists public.character_position_acquisition_privileges (
  position text primary key,
  can_command_external_purchase boolean not null default false,
  note text
);

alter table public.character_position_acquisition_privileges enable row level security;
drop policy if exists "Staff can manage acquisition position privileges"
  on public.character_position_acquisition_privileges;
create policy "Staff can manage acquisition position privileges"
  on public.character_position_acquisition_privileges for all
  to authenticated
  using (public.is_active_staff())
  with check (public.is_active_staff());
grant select, insert, update, delete
  on public.character_position_acquisition_privileges to authenticated;

insert into public.character_position_acquisition_privileges (
  position, can_command_external_purchase, note
) values
  ('เจี๋ยอวี้', true, 'มีตำแหน่งพอให้ออกหนังสือจากตำหนัก'),
  ('จิ่วผิน', true, 'พระสนมชั้นสูง'),
  ('ซื่อฝูเหริน', true, 'พระสนมชั้นสูง'),
  ('ฮองเฮา', true, 'ผู้ดูแลวังหลัง'),
  ('หัวหน้าขันที', true, 'หัวหน้าหน่วยงานที่ออกคำสั่งงานได้'),
  ('หัวหน้าองครักษ์', true, 'หัวหน้าหน่วยงานที่ออกคำสั่งงานได้'),
  ('ซ่างกง', true, 'หัวหน้าฝ่ายงานวังหลัง')
on conflict (position) do update set
  can_command_external_purchase = excluded.can_command_external_purchase,
  note = excluded.note;

alter table public.item_acquisition_requests
  add column if not exists acquisition_channel_id bigint
    references public.acquisition_channels(id) on delete set null,
  add column if not exists roll_phase text,
  add column if not exists consequence text;

alter table public.item_acquisition_requests
  drop constraint if exists item_acquisition_requests_status_check,
  add constraint item_acquisition_requests_status_check check (
    status in (
      'submitted', 'approved', 'awaiting_roll', 'risk_review', 'procuring',
      'ready', 'completed', 'rejected', 'cancelled'
    )
  ),
  drop constraint if exists item_acquisition_requests_roll_phase_check,
  add constraint item_acquisition_requests_roll_phase_check check (
    roll_phase is null or roll_phase in ('contact_and_smuggling')
  );

-- Coherent starter economy: Favor is an access/promotion threshold and is never spent.
-- RP guidance yields roughly 5-10 RP per approved contribution.
create table if not exists public.rp_reward_guidelines (
  submission_type text primary key,
  recommended_rp integer not null check (recommended_rp >= 0),
  recommended_favor integer not null check (recommended_favor >= 0),
  note text,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.rp_reward_guidelines enable row level security;
drop policy if exists "Staff can manage RP reward guidelines"
  on public.rp_reward_guidelines;
create policy "Staff can manage RP reward guidelines"
  on public.rp_reward_guidelines for all
  to authenticated
  using (public.is_active_staff())
  with check (public.is_active_staff());
grant select, insert, update, delete on public.rp_reward_guidelines to authenticated;

insert into public.rp_reward_guidelines (
  submission_type, recommended_rp, recommended_favor, note
) values
  ('โรลเพลย์', 8, 1, 'โรลที่มีเนื้อหาครบและผ่านเกณฑ์ชุมชน'),
  ('เข้าร่วมกิจกรรม', 10, 1, 'กิจกรรมที่ทีมงานประกาศ'),
  ('งานวาด / งานสร้างสรรค์', 6, 0, 'ผลงานสร้างสรรค์ที่เกี่ยวข้องกับตัวละครหรือคอมมู'),
  ('ภารกิจ', 8, 1, 'ภารกิจที่มีผลสรุปชัดเจน'),
  ('สำรวจ', 5, 0, 'การสำรวจหนึ่งครั้งที่ผ่านเงื่อนไข'),
  ('อื่น ๆ', 5, 0, 'ค่าเริ่มต้น ทีมงานปรับตามน้ำหนักงานได้')
on conflict (submission_type) do update set
  recommended_rp = excluded.recommended_rp,
  recommended_favor = excluded.recommended_favor,
  note = excluded.note,
  active = true,
  updated_at = now();

-- Repair existing sample/live catalog classifications and establish starter prices.
update public.items set
  cost = 6,
  price_currency = 'rp',
  acquisition_type = 'palace_stock',
  catalog_visibility = 'public',
  minimum_favor = 0,
  acquisition_risk_level = 1,
  auto_fulfill = true,
  acquisition_requires_roll = false
where name = 'ผ้าไหมลายเมฆ';

update public.items set
  cost = 24,
  price_currency = 'rp',
  acquisition_type = 'external_legal',
  catalog_visibility = 'public',
  minimum_favor = 0,
  acquisition_risk_level = 1,
  auto_fulfill = false,
  acquisition_requires_roll = false,
  fulfillment_days_min = 2,
  fulfillment_days_max = 5
where name = 'ปิ่นหยกขาว';

update public.items set
  cost = 30,
  price_currency = 'rp',
  acquisition_type = 'external_legal',
  catalog_visibility = 'public',
  minimum_favor = 5,
  acquisition_risk_level = 1,
  auto_fulfill = false,
  acquisition_requires_roll = false,
  fulfillment_days_min = 2,
  fulfillment_days_max = 5
where name = 'เครื่องรางคุ้มภัย';

update public.items set
  cost = 70,
  price_currency = 'rp',
  acquisition_type = 'restricted',
  catalog_visibility = 'locked',
  shop_available = false,
  minimum_favor = 20,
  acquisition_risk_level = 4,
  auto_fulfill = false,
  acquisition_requires_roll = true,
  acquisition_success_percent = 55,
  acquisition_channel_id = (
    select id from public.acquisition_channels
    where code = 'luo-jing-supply-ledger'
  ),
  failure_consequence = 'ติดต่อไม่สำเร็จ คำร้องต้องปิดและคืน RP โดยช่องทางยังคงถูกจับตา',
  critical_failure_consequence = 'ทิ้งร่องรอยในบัญชีส่งเสบียง ทีมงานสามารถเปิดเหตุการณ์ตรวจค้นหรือล็อกช่องทางชั่วคราว',
  fulfillment_days_min = 1,
  fulfillment_days_max = 3
where name = 'แผนผังทางลับ';

update public.items set
  cost = 90,
  price_currency = 'rp',
  acquisition_type = 'restricted',
  catalog_visibility = 'locked',
  shop_available = false,
  minimum_favor = 30,
  acquisition_risk_level = 5,
  auto_fulfill = false,
  acquisition_requires_roll = true,
  acquisition_success_percent = 45,
  acquisition_channel_id = (
    select id from public.acquisition_channels
    where code = 'luo-jing-supply-ledger'
  ),
  failure_consequence = 'การติดต่อหยุดลง คำร้องต้องปิดและคืน RP ก่อนยื่นใหม่ภายหลัง',
  critical_failure_consequence = 'เกิดเบาะแสของยาต้องห้าม ทีมงานสามารถเปิดเหตุการณ์ตรวจค้นและผลกระทบทางเนื้อเรื่อง',
  use_category = 'medicine',
  requires_target = true,
  requires_roll = true,
  fulfillment_days_min = 2,
  fulfillment_days_max = 4
where name = 'ยาพิษสิบชนิด';

update public.items set
  cost = 0,
  price_currency = 'rp',
  acquisition_type = 'story_only',
  shop_available = false,
  auto_fulfill = false,
  acquisition_requires_roll = false,
  minimum_favor = 0,
  acquisition_risk_level = 1
where acquisition_type = 'story_only' or use_category = 'story';

drop function if exists public.get_player_item_catalog(integer);
create function public.get_player_item_catalog(
  p_character_id integer
)
returns table (
  id bigint,
  name text,
  description text,
  cost integer,
  price_currency text,
  acquisition_type text,
  catalog_visibility text,
  acquisition_requires_roll boolean,
  minimum_favor integer,
  fulfillment_days_min integer,
  fulfillment_days_max integer,
  is_limited boolean,
  stock_quantity integer,
  use_category text,
  unlocked boolean,
  can_request boolean,
  action_label text,
  acquisition_channel_name text,
  acquisition_channel_role text,
  acquisition_channel_access_reason text,
  acquisition_channel_motivation text,
  acquisition_unlock_method text,
  acquisition_risk_summary text,
  acquisition_risk_level integer
)
language sql
security definer
set search_path = public
stable
as $$
  with character_row as (
    select
      character.id,
      character.position,
      coalesce(character.favor, 0) as favor,
      coalesce(privilege.can_command_external_purchase, false) as can_command
    from public.characters character
    left join public.character_position_acquisition_privileges privilege
      on privilege.position = character.position
    where character.id = p_character_id
  )
  select
    item.id,
    case when item.catalog_visibility = 'locked' and unlock.id is null
      then 'ช่องทางที่ยังไม่เปิดเผย' else item.name end,
    case when item.catalog_visibility = 'locked' and unlock.id is null
      then 'ต้องค้นหาเบาะแสหรือสร้างความไว้วางใจก่อนจึงจะติดต่อช่องทางนี้ได้'
      else item.description end,
    item.cost,
    item.price_currency,
    item.acquisition_type,
    item.catalog_visibility,
    item.acquisition_requires_roll,
    item.minimum_favor,
    case
      when item.acquisition_type = 'external_legal' and character_row.can_command
        then greatest(0, item.fulfillment_days_min - 1)
      else item.fulfillment_days_min
    end,
    case
      when item.acquisition_type = 'external_legal' and character_row.can_command
        then greatest(
          greatest(0, item.fulfillment_days_min - 1),
          item.fulfillment_days_max - 2
        )
      else item.fulfillment_days_max
    end,
    item.is_limited,
    item.stock_quantity,
    item.use_category,
    unlock.id is not null,
    case
      when item.acquisition_type = 'story_only' then false
      when item.catalog_visibility = 'locked' and unlock.id is null then false
      when character_row.favor < item.minimum_favor then false
      when item.is_limited and item.stock_quantity <= 0 then false
      else true
    end,
    case
      when item.acquisition_type = 'story_only' then 'ได้รับจากการสำรวจเท่านั้น'
      when item.catalog_visibility = 'locked' and unlock.id is null
        then 'ยังไม่ปลดล็อกช่องทาง'
      when character_row.favor < item.minimum_favor
        then 'โปรดปรานยังไม่ถึงเกณฑ์'
      when item.acquisition_type = 'palace_stock' then 'เบิกจากคลัง'
      when item.acquisition_type = 'external_legal' and character_row.can_command
        then 'ออกคำสั่งให้จัดซื้อ'
      when item.acquisition_type = 'external_legal' then 'ส่งคำขอจัดซื้อ'
      when item.acquisition_type = 'restricted' then 'ติดต่อคนกลาง'
      else 'ไม่สามารถขอได้'
    end,
    case when unlock.id is not null then channel.npc_name else null end,
    case when unlock.id is not null then channel.npc_role else null end,
    case when unlock.id is not null then channel.access_reason else null end,
    case when unlock.id is not null then channel.motivation else null end,
    case when unlock.id is not null then channel.unlock_method else null end,
    case when unlock.id is not null then channel.risk_summary else null end,
    item.acquisition_risk_level
  from public.items item
  cross join character_row
  left join public.character_catalog_unlocks unlock
    on unlock.character_id = character_row.id and unlock.item_id = item.id
  left join public.acquisition_channels channel
    on channel.id = item.acquisition_channel_id and channel.active
  where item.active
    and item.catalog_visibility <> 'staff_only'
    and (
      item.shop_available
      or item.acquisition_type = 'story_only'
      or item.catalog_visibility = 'locked'
    )
  order by
    case item.acquisition_type
      when 'palace_stock' then 1
      when 'external_legal' then 2
      when 'restricted' then 3
      else 4
    end,
    item.name;
$$;

create or replace function public.submit_item_acquisition_request(
  p_character_id integer,
  p_item_id bigint,
  p_quantity integer default 1,
  p_player_note text default null
)
returns public.item_acquisition_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  character_row public.characters;
  item_row public.items;
  unlock_row public.character_catalog_unlocks;
  request_row public.item_acquisition_requests;
  route_value text;
  should_auto_fulfill boolean;
  can_command boolean := false;
  total_cost integer;
begin
  if p_quantity <= 0 then raise exception 'Quantity must be positive'; end if;

  select * into character_row from public.characters
  where id = p_character_id for update;
  if not found then raise exception 'Character not found'; end if;

  select * into item_row from public.items
  where id = p_item_id and active for update;
  if not found then raise exception 'Catalog item not found'; end if;

  if item_row.acquisition_type = 'story_only' then
    raise exception 'Story items cannot be requested from the catalog';
  end if;
  if item_row.catalog_visibility = 'staff_only' then
    raise exception 'Catalog item is not available';
  end if;
  if item_row.catalog_visibility = 'locked' then
    select * into unlock_row from public.character_catalog_unlocks
    where character_id = p_character_id and item_id = p_item_id;
    if not found then raise exception 'Acquisition channel is locked'; end if;
  end if;
  if coalesce(character_row.favor, 0) < item_row.minimum_favor then
    raise exception 'Insufficient Favor threshold';
  end if;
  if item_row.price_currency <> 'rp' then
    raise exception 'Catalog acquisition must use RP; Favor is an access threshold';
  end if;

  select exists (
    select 1
    from public.character_position_acquisition_privileges privilege
    where privilege.position = character_row.position
      and privilege.can_command_external_purchase
  ) into can_command;

  total_cost := item_row.cost * p_quantity;
  route_value := case
    when item_row.acquisition_type = 'palace_stock' then 'requisition'
    when item_row.acquisition_type = 'external_legal' and can_command then 'command'
    when item_row.acquisition_type = 'external_legal' then 'procurement'
    else 'restricted_contact'
  end;
  should_auto_fulfill := item_row.acquisition_type = 'palace_stock'
    and item_row.auto_fulfill and not item_row.acquisition_requires_roll;

  if should_auto_fulfill then
    if coalesce(character_row.rp, 0) < total_cost then raise exception 'Insufficient RP'; end if;
    if item_row.is_limited and item_row.stock_quantity < p_quantity then
      raise exception 'Item is out of stock';
    end if;
    update public.characters set rp = coalesce(rp, 0) - total_cost
      where id = p_character_id;
    if item_row.is_limited then
      update public.items set stock_quantity = stock_quantity - p_quantity, updated_at = now()
      where id = p_item_id;
    end if;
    insert into public.character_inventory (character_id, item_name, quantity)
    values (p_character_id, item_row.name, p_quantity)
    on conflict (character_id, item_name)
    do update set quantity = public.character_inventory.quantity + excluded.quantity;
    insert into public.item_acquisition_requests (
      character_id, item_id, quantity, request_route, status, player_note,
      charged_currency, charged_amount, item_granted, requested_by, completed_at,
      acquisition_channel_id
    ) values (
      p_character_id, p_item_id, p_quantity, route_value, 'completed',
      nullif(btrim(p_player_note), ''), 'rp', total_cost, true, auth.uid(), now(),
      item_row.acquisition_channel_id
    ) returning * into request_row;
    insert into public.inventory_transactions (
      item_id, character_id, quantity_change, transaction_type, note
    ) values (
      p_item_id, p_character_id, -p_quantity, 'purchase',
      'เบิกจากคลังผ่านแคตตาล็อก · ' || total_cost || ' RP'
    );
  else
    insert into public.item_acquisition_requests (
      character_id, item_id, quantity, request_route, status, player_note,
      success_chance_percent, requested_by, acquisition_channel_id, roll_phase
    ) values (
      p_character_id, p_item_id, p_quantity, route_value, 'submitted',
      nullif(btrim(p_player_note), ''),
      case when item_row.acquisition_requires_roll
        then item_row.acquisition_success_percent else null end,
      auth.uid(), item_row.acquisition_channel_id,
      case when item_row.acquisition_requires_roll
        then 'contact_and_smuggling' else null end
    ) returning * into request_row;
  end if;

  insert into public.character_history (character_id, action, value, type)
  values (
    p_character_id,
    case when should_auto_fulfill then 'เบิกไอเท็ม' else 'ส่งคำร้องจัดหาไอเท็ม' end,
    item_row.name || ' ×' || p_quantity,
    'item_acquisition'
  );
  return request_row;
end;
$$;

drop function if exists public.get_player_item_acquisition_requests(integer);
create function public.get_player_item_acquisition_requests(
  p_character_id integer
)
returns table (
  id bigint,
  item_name text,
  quantity integer,
  request_route text,
  status text,
  staff_note text,
  charged_amount integer,
  resolution_roll integer,
  resolution_outcome text,
  roll_phase text,
  consequence text,
  acquisition_channel_name text,
  submitted_at timestamptz,
  updated_at timestamptz
)
language sql
security definer
set search_path = public
stable
as $$
  select
    request.id,
    item.name,
    request.quantity,
    request.request_route,
    request.status,
    request.staff_note,
    request.charged_amount,
    request.resolution_roll,
    request.resolution_outcome,
    request.roll_phase,
    request.consequence,
    channel.npc_name,
    request.submitted_at,
    request.updated_at
  from public.item_acquisition_requests request
  join public.items item on item.id = request.item_id
  left join public.acquisition_channels channel
    on channel.id = request.acquisition_channel_id
  where request.character_id = p_character_id
  order by request.submitted_at desc
  limit 20;
$$;

create or replace function public.roll_item_acquisition(
  p_request_id bigint
)
returns public.item_acquisition_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  request_row public.item_acquisition_requests;
  item_row public.items;
  rolled_value integer;
  outcome_value text;
  consequence_value text;
begin
  if not public.is_active_staff() then raise exception 'Staff access required'; end if;
  select * into request_row from public.item_acquisition_requests
  where id = p_request_id for update;
  if not found or request_row.status <> 'awaiting_roll' then
    raise exception 'Request is not awaiting a roll';
  end if;
  if request_row.resolution_roll is not null then raise exception 'Request already rolled'; end if;
  select * into item_row from public.items where id = request_row.item_id;

  rolled_value := floor(random() * 100 + 1)::integer;
  outcome_value := case
    when rolled_value <= 5 then 'critical_success'
    when rolled_value <= request_row.success_chance_percent then 'success'
    when rolled_value >= 96 then 'critical_failure'
    else 'failure'
  end;
  consequence_value := case outcome_value
    when 'critical_success' then 'ติดต่อและลักลอบสำเร็จโดยไม่ทิ้งร่องรอย'
    when 'success' then 'ติดต่อและลักลอบสำเร็จ ดำเนินการจัดหาต่อได้'
    when 'critical_failure' then coalesce(
      item_row.critical_failure_consequence,
      'ล้มเหลวร้ายแรงและเกิดเบาะแสให้ฝ่ายตรวจการติดตาม'
    )
    else coalesce(item_row.failure_consequence, 'การจัดหาล้มเหลวและต้องปิดคำร้อง')
  end;

  update public.item_acquisition_requests set
    resolution_roll = rolled_value,
    resolution_outcome = outcome_value,
    consequence = consequence_value,
    status = case when outcome_value in ('success', 'critical_success')
      then 'procuring' else 'risk_review' end,
    reviewed_by = auth.uid(),
    updated_at = now()
  where id = p_request_id
  returning * into request_row;
  return request_row;
end;
$$;

revoke all on function public.get_player_item_catalog(integer) from public;
revoke all on function public.submit_item_acquisition_request(integer, bigint, integer, text) from public;
revoke all on function public.get_player_item_acquisition_requests(integer) from public;
revoke all on function public.roll_item_acquisition(bigint) from public;
grant execute on function public.get_player_item_catalog(integer) to anon, authenticated;
grant execute on function public.submit_item_acquisition_request(integer, bigint, integer, text) to anon, authenticated;
grant execute on function public.get_player_item_acquisition_requests(integer) to anon, authenticated;
grant execute on function public.roll_item_acquisition(bigint) to authenticated;

commit;
