create table if not exists public.staff_members (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.rp_submissions (
  id bigint generated by default as identity primary key,
  character_id integer not null references public.characters(id) on delete cascade,
  requested_by uuid references auth.users(id) on delete set null,
  role_url text not null,
  submission_type text not null default 'โรลทั่วไป',
  participant_names text,
  player_note text,
  status text not null default 'pending'
    check (status in ('pending', 'revision', 'approved', 'rejected')),
  awarded_rp integer not null default 0 check (awarded_rp >= 0),
  awarded_favor integer not null default 0 check (awarded_favor >= 0),
  staff_note text,
  reviewed_by uuid references auth.users(id) on delete set null,
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  updated_at timestamptz not null default now()
);

create unique index if not exists rp_submissions_unique_role_url
  on public.rp_submissions (lower(role_url));

create index if not exists rp_submissions_status_submitted_at
  on public.rp_submissions (status, submitted_at desc);

alter table public.staff_members enable row level security;
alter table public.rp_submissions enable row level security;

create or replace function public.is_active_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.staff_members
    where user_id = auth.uid() and active
  );
$$;

revoke all on function public.is_active_staff() from public;
grant execute on function public.is_active_staff() to authenticated;

create policy "Staff can view staff membership"
  on public.staff_members for select
  to authenticated
  using (public.is_active_staff());

create policy "Staff can view all RP submissions"
  on public.rp_submissions for select
  to authenticated
  using (public.is_active_staff());

create policy "Players can view their own RP submissions"
  on public.rp_submissions for select
  to authenticated
  using (requested_by = auth.uid());

create policy "Players can submit their own RP"
  on public.rp_submissions for insert
  to authenticated
  with check (requested_by = auth.uid() and status = 'pending');

create or replace function public.review_rp_submission(
  p_submission_id bigint,
  p_status text,
  p_rp integer default 0,
  p_favor integer default 0,
  p_note text default null
)
returns public.rp_submissions
language plpgsql
security definer
set search_path = public
as $$
declare
  submission public.rp_submissions;
begin
  if not exists (
    select 1 from public.staff_members
    where user_id = auth.uid() and active
  ) then
    raise exception 'Staff access required';
  end if;

  if p_status not in ('approved', 'revision', 'rejected') then
    raise exception 'Invalid review status';
  end if;

  select * into submission
  from public.rp_submissions
  where id = p_submission_id
  for update;

  if not found then
    raise exception 'Submission not found';
  end if;

  if submission.status = 'approved' then
    raise exception 'Submission has already been approved';
  end if;

  if p_status = 'approved' then
    update public.characters
    set
      rp = coalesce(rp, 0) + greatest(coalesce(p_rp, 0), 0),
      favor = coalesce(favor, 0) + greatest(coalesce(p_favor, 0), 0)
    where id = submission.character_id;

    if coalesce(p_rp, 0) > 0 then
      insert into public.character_history (character_id, action, value, type)
      values (
        submission.character_id,
        'อนุมัติโรล · ' || coalesce(nullif(p_note, ''), submission.submission_type),
        '+' || p_rp || ' RP',
        'rp'
      );
    end if;

    if coalesce(p_favor, 0) > 0 then
      insert into public.character_history (character_id, action, value, type)
      values (
        submission.character_id,
        'อนุมัติโรล · ' || coalesce(nullif(p_note, ''), submission.submission_type),
        '+' || p_favor || ' Favor',
        'favor'
      );
    end if;
  end if;

  update public.rp_submissions
  set
    status = p_status,
    awarded_rp = case when p_status = 'approved' then greatest(coalesce(p_rp, 0), 0) else 0 end,
    awarded_favor = case when p_status = 'approved' then greatest(coalesce(p_favor, 0), 0) else 0 end,
    staff_note = nullif(p_note, ''),
    reviewed_by = auth.uid(),
    reviewed_at = now(),
    updated_at = now()
  where id = p_submission_id
  returning * into submission;

  return submission;
end;
$$;

revoke all on function public.review_rp_submission(bigint, text, integer, integer, text)
  from public;
grant execute on function public.review_rp_submission(bigint, text, integer, integer, text)
  to authenticated;
