-- Run this file after the existing item, inventory, and staff migrations.
-- It adds IC acquisition routes without changing the older migration files.

begin;

-- A shared role/event link may be submitted once by each participating character.
drop index if exists public.rp_submissions_unique_role_url;
create unique index if not exists rp_submissions_unique_character_role_url
  on public.rp_submissions (character_id, lower(role_url));

alter table public.items
  add column if not exists acquisition_type text not null default 'palace_stock',
  add column if not exists catalog_visibility text not null default 'public',
  add column if not exists acquisition_requires_roll boolean not null default false,
  add column if not exists acquisition_success_percent integer not null default 70,
  add column if not exists minimum_favor integer not null default 0,
  add column if not exists command_favor_threshold integer not null default 20,
  add column if not exists fulfillment_days_min integer not null default 0,
  add column if not exists fulfillment_days_max integer not null default 1,
  add column if not exists auto_fulfill boolean not null default true;

alter table public.items
  drop constraint if exists items_acquisition_type_check,
  add constraint items_acquisition_type_check check (
    acquisition_type in ('palace_stock', 'external_legal', 'restricted', 'story_only')
  ),
  drop constraint if exists items_catalog_visibility_check,
  add constraint items_catalog_visibility_check check (
    catalog_visibility in ('public', 'locked', 'staff_only')
  ),
  drop constraint if exists items_acquisition_success_percent_check,
  add constraint items_acquisition_success_percent_check check (
    acquisition_success_percent between 5 and 95
  ),
  drop constraint if exists items_minimum_favor_check,
  add constraint items_minimum_favor_check check (minimum_favor >= 0),
  drop constraint if exists items_command_favor_threshold_check,
  add constraint items_command_favor_threshold_check check (command_favor_threshold >= 0),
  drop constraint if exists items_fulfillment_days_check,
  add constraint items_fulfillment_days_check check (
    fulfillment_days_min >= 0 and fulfillment_days_max >= fulfillment_days_min
  );

update public.items
set
  acquisition_type = case
    when use_category = 'story' then 'story_only'
    when use_category = 'secret' then 'restricted'
    else acquisition_type
  end,
  catalog_visibility = case
    when use_category = 'secret' then 'locked'
    else catalog_visibility
  end,
  auto_fulfill = case
    when use_category in ('story', 'secret') then false
    else auto_fulfill
  end,
  fulfillment_days_min = case
    when use_category = 'secret' then 1
    else fulfillment_days_min
  end,
  fulfillment_days_max = case
    when use_category = 'secret' then 3
    else fulfillment_days_max
  end;

-- Reclassify the existing mock catalog so the new page has one example of each route.
update public.items set
  acquisition_type = 'palace_stock', catalog_visibility = 'public',
  shop_available = true, price_currency = 'rp', cost = 0,
  auto_fulfill = true, fulfillment_days_min = 0, fulfillment_days_max = 0
where name = 'ห่อยาสมุนไพรชั้นดี';

update public.items set
  acquisition_type = 'palace_stock', catalog_visibility = 'public',
  shop_available = true, price_currency = 'rp', cost = 5,
  auto_fulfill = true, fulfillment_days_min = 0, fulfillment_days_max = 1
where name = 'ผ้าไหมลายเมฆ';

update public.items set
  acquisition_type = 'external_legal', catalog_visibility = 'public',
  shop_available = true, price_currency = 'rp', cost = 20,
  auto_fulfill = false, fulfillment_days_min = 2, fulfillment_days_max = 5
where name = 'ปิ่นหยกขาว';

update public.items set
  acquisition_type = 'external_legal', catalog_visibility = 'public',
  shop_available = true, price_currency = 'rp', cost = 25,
  minimum_favor = 5, auto_fulfill = false,
  fulfillment_days_min = 2, fulfillment_days_max = 5
where name = 'เครื่องรางคุ้มภัย';

update public.items set
  acquisition_type = 'restricted', catalog_visibility = 'locked',
  shop_available = false, price_currency = 'rp', cost = 60,
  auto_fulfill = false, acquisition_requires_roll = true,
  acquisition_success_percent = 55, fulfillment_days_min = 1,
  fulfillment_days_max = 3
where name = 'แผนผังทางลับ';

update public.items set
  acquisition_type = 'story_only', catalog_visibility = 'public',
  shop_available = false, auto_fulfill = false
where name in (
  'ตราผ่านทางวังชั้นใน', 'จดหมายปิดผนึก', 'ถุงเงินรางวัล',
  'ตำรับยาหายาก', 'เบาะแสลับจากวังหลัง'
);

create table if not exists public.character_catalog_unlocks (
  id bigint generated by default as identity primary key,
  character_id integer not null references public.characters(id) on delete cascade,
  item_id bigint not null references public.items(id) on delete cascade,
  source text,
  note text,
  unlocked_by uuid references auth.users(id) on delete set null,
  unlocked_at timestamptz not null default now(),
  unique (character_id, item_id)
);

create table if not exists public.item_acquisition_requests (
  id bigint generated by default as identity primary key,
  character_id integer not null references public.characters(id) on delete restrict,
  item_id bigint not null references public.items(id) on delete restrict,
  quantity integer not null default 1 check (quantity > 0),
  request_route text not null check (
    request_route in ('requisition', 'procurement', 'command', 'restricted_contact')
  ),
  status text not null default 'submitted' check (
    status in (
      'submitted', 'approved', 'awaiting_roll', 'procuring', 'ready',
      'completed', 'rejected', 'cancelled'
    )
  ),
  player_note text,
  staff_note text,
  charged_currency text check (charged_currency in ('rp')),
  charged_amount integer not null default 0 check (charged_amount >= 0),
  stock_reserved boolean not null default false,
  item_granted boolean not null default false,
  success_chance_percent integer check (success_chance_percent between 5 and 95),
  resolution_roll integer check (resolution_roll between 1 and 100),
  resolution_outcome text check (
    resolution_outcome in ('critical_success', 'success', 'failure', 'critical_failure')
  ),
  requested_by uuid references auth.users(id) on delete set null,
  reviewed_by uuid references auth.users(id) on delete set null,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists item_acquisition_requests_status_submitted
  on public.item_acquisition_requests (status, submitted_at desc);
create index if not exists item_acquisition_requests_character_submitted
  on public.item_acquisition_requests (character_id, submitted_at desc);

alter table public.character_catalog_unlocks enable row level security;
alter table public.item_acquisition_requests enable row level security;

drop policy if exists "Staff can manage catalog unlocks"
  on public.character_catalog_unlocks;
create policy "Staff can manage catalog unlocks"
  on public.character_catalog_unlocks for all
  to authenticated
  using (public.is_active_staff())
  with check (public.is_active_staff());

drop policy if exists "Staff can manage acquisition requests"
  on public.item_acquisition_requests;
create policy "Staff can manage acquisition requests"
  on public.item_acquisition_requests for all
  to authenticated
  using (public.is_active_staff())
  with check (public.is_active_staff());

create or replace function public.get_player_item_catalog(
  p_character_id integer
)
returns table (
  id bigint,
  name text,
  description text,
  cost integer,
  price_currency text,
  acquisition_type text,
  catalog_visibility text,
  acquisition_requires_roll boolean,
  minimum_favor integer,
  fulfillment_days_min integer,
  fulfillment_days_max integer,
  is_limited boolean,
  stock_quantity integer,
  use_category text,
  unlocked boolean,
  can_request boolean,
  action_label text
)
language sql
security definer
set search_path = public
stable
as $$
  with character_row as (
    select character.id, coalesce(character.favor, 0) as favor
    from public.characters character
    where character.id = p_character_id
  )
  select
    item.id,
    case
      when item.catalog_visibility = 'locked' and unlock.id is null
        then 'ช่องทางที่ยังไม่เปิดเผย'
      else item.name
    end,
    case
      when item.catalog_visibility = 'locked' and unlock.id is null
        then 'ต้องค้นหาเบาะแสหรือสร้างความไว้วางใจก่อนจึงจะติดต่อช่องทางนี้ได้'
      else item.description
    end,
    item.cost,
    item.price_currency,
    item.acquisition_type,
    item.catalog_visibility,
    item.acquisition_requires_roll,
    item.minimum_favor,
    item.fulfillment_days_min,
    item.fulfillment_days_max,
    item.is_limited,
    item.stock_quantity,
    item.use_category,
    unlock.id is not null,
    case
      when item.acquisition_type = 'story_only' then false
      when item.catalog_visibility = 'locked' and unlock.id is null then false
      when character_row.favor < item.minimum_favor then false
      when item.is_limited and item.stock_quantity <= 0 then false
      else true
    end,
    case
      when item.acquisition_type = 'story_only' then 'ได้รับจากการสำรวจเท่านั้น'
      when item.catalog_visibility = 'locked' and unlock.id is null
        then 'ยังไม่ปลดล็อกช่องทาง'
      when character_row.favor < item.minimum_favor
        then 'โปรดปรานยังไม่ถึงเกณฑ์'
      when item.acquisition_type = 'palace_stock' then 'เบิกจากคลัง'
      when item.acquisition_type = 'external_legal'
        and character_row.favor >= item.command_favor_threshold
        then 'ออกคำสั่งให้จัดซื้อ'
      when item.acquisition_type = 'external_legal' then 'ส่งคำขอจัดซื้อ'
      when item.acquisition_type = 'restricted' then 'ติดต่อคนกลาง'
      else 'ไม่สามารถขอได้'
    end
  from public.items item
  cross join character_row
  left join public.character_catalog_unlocks unlock
    on unlock.character_id = character_row.id and unlock.item_id = item.id
  where item.active
    and item.catalog_visibility <> 'staff_only'
    and (
      item.shop_available
      or item.acquisition_type = 'story_only'
      or item.catalog_visibility = 'locked'
    )
  order by
    case item.acquisition_type
      when 'palace_stock' then 1
      when 'external_legal' then 2
      when 'restricted' then 3
      else 4
    end,
    item.name;
$$;

create or replace function public.submit_item_acquisition_request(
  p_character_id integer,
  p_item_id bigint,
  p_quantity integer default 1,
  p_player_note text default null
)
returns public.item_acquisition_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  character_row public.characters;
  item_row public.items;
  unlock_row public.character_catalog_unlocks;
  request_row public.item_acquisition_requests;
  route_value text;
  should_auto_fulfill boolean;
  total_cost integer;
begin
  if p_quantity <= 0 then
    raise exception 'Quantity must be positive';
  end if;

  select * into character_row
  from public.characters
  where id = p_character_id
  for update;
  if not found then raise exception 'Character not found'; end if;

  select * into item_row
  from public.items
  where id = p_item_id and active
  for update;
  if not found then raise exception 'Catalog item not found'; end if;

  if item_row.acquisition_type = 'story_only' then
    raise exception 'Story items cannot be requested from the catalog';
  end if;
  if item_row.catalog_visibility = 'staff_only' then
    raise exception 'Catalog item is not available';
  end if;
  if item_row.catalog_visibility = 'locked' then
    select * into unlock_row
    from public.character_catalog_unlocks
    where character_id = p_character_id and item_id = p_item_id;
    if not found then raise exception 'Acquisition channel is locked'; end if;
  end if;
  if coalesce(character_row.favor, 0) < item_row.minimum_favor then
    raise exception 'Insufficient Favor threshold';
  end if;
  if item_row.price_currency <> 'rp' then
    raise exception 'Catalog acquisition must use RP; Favor is an access threshold';
  end if;

  total_cost := item_row.cost * p_quantity;
  route_value := case
    when item_row.acquisition_type = 'palace_stock' then 'requisition'
    when item_row.acquisition_type = 'external_legal'
      and coalesce(character_row.favor, 0) >= item_row.command_favor_threshold
      then 'command'
    when item_row.acquisition_type = 'external_legal' then 'procurement'
    else 'restricted_contact'
  end;
  should_auto_fulfill := item_row.acquisition_type = 'palace_stock'
    and item_row.auto_fulfill
    and not item_row.acquisition_requires_roll;

  if should_auto_fulfill then
    if coalesce(character_row.rp, 0) < total_cost then
      raise exception 'Insufficient RP';
    end if;
    if item_row.is_limited and item_row.stock_quantity < p_quantity then
      raise exception 'Item is out of stock';
    end if;

    update public.characters
    set rp = coalesce(rp, 0) - total_cost
    where id = p_character_id;
    if item_row.is_limited then
      update public.items
      set stock_quantity = stock_quantity - p_quantity, updated_at = now()
      where id = p_item_id;
    end if;
    insert into public.character_inventory (character_id, item_name, quantity)
    values (p_character_id, item_row.name, p_quantity)
    on conflict (character_id, item_name)
    do update set quantity = public.character_inventory.quantity + excluded.quantity;

    insert into public.item_acquisition_requests (
      character_id, item_id, quantity, request_route, status, player_note,
      charged_currency, charged_amount, item_granted, requested_by, completed_at
    ) values (
      p_character_id, p_item_id, p_quantity, route_value, 'completed',
      nullif(btrim(p_player_note), ''), 'rp', total_cost, true, auth.uid(), now()
    ) returning * into request_row;

    insert into public.inventory_transactions (
      item_id, character_id, quantity_change, transaction_type, note
    ) values (
      p_item_id, p_character_id, -p_quantity, 'purchase',
      'เบิกจากคลังผ่านแคตตาล็อก · ' || total_cost || ' RP'
    );
  else
    insert into public.item_acquisition_requests (
      character_id, item_id, quantity, request_route, status, player_note,
      success_chance_percent, requested_by
    ) values (
      p_character_id, p_item_id, p_quantity, route_value, 'submitted',
      nullif(btrim(p_player_note), ''),
      case when item_row.acquisition_requires_roll
        then item_row.acquisition_success_percent else null end,
      auth.uid()
    ) returning * into request_row;
  end if;

  insert into public.character_history (character_id, action, value, type)
  values (
    p_character_id,
    case when should_auto_fulfill then 'เบิกไอเท็ม' else 'ส่งคำร้องจัดหาไอเท็ม' end,
    item_row.name || ' ×' || p_quantity,
    'item_acquisition'
  );

  return request_row;
end;
$$;

create or replace function public.get_player_item_acquisition_requests(
  p_character_id integer
)
returns table (
  id bigint,
  item_name text,
  quantity integer,
  request_route text,
  status text,
  staff_note text,
  charged_amount integer,
  resolution_roll integer,
  resolution_outcome text,
  submitted_at timestamptz,
  updated_at timestamptz
)
language sql
security definer
set search_path = public
stable
as $$
  select
    request.id,
    item.name,
    request.quantity,
    request.request_route,
    request.status,
    request.staff_note,
    request.charged_amount,
    request.resolution_roll,
    request.resolution_outcome,
    request.submitted_at,
    request.updated_at
  from public.item_acquisition_requests request
  join public.items item on item.id = request.item_id
  where request.character_id = p_character_id
  order by request.submitted_at desc
  limit 20;
$$;

create or replace function public.review_item_acquisition_request(
  p_request_id bigint,
  p_status text,
  p_staff_note text default null
)
returns public.item_acquisition_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  request_row public.item_acquisition_requests;
  item_row public.items;
  character_row public.characters;
  total_cost integer;
  target_status text := p_status;
begin
  if not public.is_active_staff() then raise exception 'Staff access required'; end if;
  if p_status not in (
    'approved', 'awaiting_roll', 'procuring', 'ready', 'completed', 'rejected', 'cancelled'
  ) then raise exception 'Invalid acquisition status'; end if;

  select * into request_row
  from public.item_acquisition_requests
  where id = p_request_id
  for update;
  if not found then raise exception 'Acquisition request not found'; end if;
  if request_row.status in ('completed', 'rejected', 'cancelled') then
    raise exception 'Acquisition request is already closed';
  end if;

  select * into item_row from public.items where id = request_row.item_id for update;
  select * into character_row from public.characters
    where id = request_row.character_id for update;
  total_cost := item_row.cost * request_row.quantity;

  if p_status in ('approved', 'awaiting_roll', 'procuring', 'ready', 'completed')
    and request_row.charged_currency is null then
    if coalesce(character_row.rp, 0) < total_cost then raise exception 'Insufficient RP'; end if;
    if item_row.is_limited and item_row.stock_quantity < request_row.quantity then
      raise exception 'Item is out of stock';
    end if;
    update public.characters set rp = coalesce(rp, 0) - total_cost
      where id = request_row.character_id;
    if item_row.is_limited then
      update public.items
      set stock_quantity = stock_quantity - request_row.quantity, updated_at = now()
      where id = request_row.item_id;
      request_row.stock_reserved := true;
    end if;
    request_row.charged_amount := total_cost;
    request_row.charged_currency := 'rp';
  end if;

  if p_status = 'approved' and item_row.acquisition_requires_roll then
    target_status := 'awaiting_roll';
  elsif p_status = 'approved' then
    target_status := 'procuring';
  end if;

  if p_status = 'completed' then
    if item_row.acquisition_requires_roll
      and (
        request_row.resolution_outcome is null
        or request_row.resolution_outcome not in ('success', 'critical_success')
      ) then
      raise exception 'A successful acquisition roll is required';
    end if;
    insert into public.character_inventory (character_id, item_name, quantity)
    values (request_row.character_id, item_row.name, request_row.quantity)
    on conflict (character_id, item_name)
    do update set quantity = public.character_inventory.quantity + excluded.quantity;
    insert into public.inventory_transactions (
      item_id, character_id, quantity_change, transaction_type, note, created_by
    ) values (
      request_row.item_id, request_row.character_id, -request_row.quantity,
      'purchase', coalesce(nullif(btrim(p_staff_note), ''), 'จัดหาไอเท็มสำเร็จ'), auth.uid()
    );
    request_row.item_granted := true;
  end if;

  if p_status in ('rejected', 'cancelled') and request_row.charged_currency is not null then
    update public.characters
    set rp = coalesce(rp, 0) + request_row.charged_amount
    where id = request_row.character_id;
    if request_row.stock_reserved then
      update public.items
      set stock_quantity = stock_quantity + request_row.quantity, updated_at = now()
      where id = request_row.item_id;
    end if;
    request_row.charged_amount := 0;
    request_row.charged_currency := null;
    request_row.stock_reserved := false;
  end if;

  update public.item_acquisition_requests
  set
    status = target_status,
    staff_note = nullif(btrim(p_staff_note), ''),
    charged_currency = request_row.charged_currency,
    charged_amount = request_row.charged_amount,
    stock_reserved = request_row.stock_reserved,
    item_granted = request_row.item_granted,
    reviewed_by = auth.uid(),
    updated_at = now(),
    completed_at = case when target_status = 'completed' then now() else null end
  where id = p_request_id
  returning * into request_row;

  return request_row;
end;
$$;

create or replace function public.roll_item_acquisition(
  p_request_id bigint
)
returns public.item_acquisition_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  request_row public.item_acquisition_requests;
  rolled_value integer;
  outcome_value text;
begin
  if not public.is_active_staff() then raise exception 'Staff access required'; end if;
  select * into request_row
  from public.item_acquisition_requests
  where id = p_request_id
  for update;
  if not found or request_row.status <> 'awaiting_roll' then
    raise exception 'Request is not awaiting a roll';
  end if;
  if request_row.resolution_roll is not null then raise exception 'Request already rolled'; end if;

  rolled_value := floor(random() * 100 + 1)::integer;
  outcome_value := case
    when rolled_value <= 5 then 'critical_success'
    when rolled_value <= request_row.success_chance_percent then 'success'
    when rolled_value >= 96 then 'critical_failure'
    else 'failure'
  end;

  update public.item_acquisition_requests
  set
    resolution_roll = rolled_value,
    resolution_outcome = outcome_value,
    status = case when outcome_value in ('success', 'critical_success')
      then 'procuring' else 'awaiting_roll' end,
    reviewed_by = auth.uid(),
    updated_at = now()
  where id = p_request_id
  returning * into request_row;
  return request_row;
end;
$$;

create or replace function public.unlock_character_catalog_item(
  p_character_id integer,
  p_item_id bigint,
  p_source text default null,
  p_note text default null
)
returns public.character_catalog_unlocks
language plpgsql
security definer
set search_path = public
as $$
declare unlock_row public.character_catalog_unlocks;
begin
  if not public.is_active_staff() then raise exception 'Staff access required'; end if;
  insert into public.character_catalog_unlocks (
    character_id, item_id, source, note, unlocked_by
  ) values (
    p_character_id, p_item_id, nullif(btrim(p_source), ''),
    nullif(btrim(p_note), ''), auth.uid()
  )
  on conflict (character_id, item_id) do update set
    source = excluded.source,
    note = excluded.note,
    unlocked_by = auth.uid(),
    unlocked_at = now()
  returning * into unlock_row;
  return unlock_row;
end;
$$;

revoke all on function public.get_player_item_catalog(integer) from public;
revoke all on function public.submit_item_acquisition_request(integer, bigint, integer, text) from public;
revoke all on function public.get_player_item_acquisition_requests(integer) from public;
revoke all on function public.review_item_acquisition_request(bigint, text, text) from public;
revoke all on function public.roll_item_acquisition(bigint) from public;
revoke all on function public.unlock_character_catalog_item(integer, bigint, text, text) from public;

grant execute on function public.get_player_item_catalog(integer) to anon, authenticated;
grant execute on function public.submit_item_acquisition_request(integer, bigint, integer, text) to anon, authenticated;
grant execute on function public.get_player_item_acquisition_requests(integer) to anon, authenticated;
grant execute on function public.review_item_acquisition_request(bigint, text, text) to authenticated;
grant execute on function public.roll_item_acquisition(bigint) to authenticated;
grant execute on function public.unlock_character_catalog_item(integer, bigint, text, text) to authenticated;

-- Keep the player inventory response aligned with the transfer rule used by the UI.
drop function if exists public.get_character_inventory_details(integer);
create function public.get_character_inventory_details(
  p_character_id integer
)
returns table (
  inventory_id bigint,
  item_id bigint,
  item_name text,
  quantity integer,
  description text,
  use_category text,
  default_channel text,
  requires_target boolean,
  requires_roll boolean,
  transferable boolean
)
language sql
security definer
set search_path = public
stable
as $$
  select
    inventory.id::bigint,
    catalog.id::bigint,
    inventory.item_name,
    inventory.quantity,
    catalog.description,
    coalesce(catalog.use_category, 'general'),
    catalog.default_channel,
    coalesce(catalog.requires_target, false),
    coalesce(catalog.requires_roll, false),
    coalesce(catalog.transferable, true)
  from public.character_inventory inventory
  left join public.items catalog on catalog.name = inventory.item_name
  where inventory.character_id = p_character_id and inventory.quantity > 0
  order by inventory.item_name;
$$;
revoke all on function public.get_character_inventory_details(integer) from public;
grant execute on function public.get_character_inventory_details(integer) to anon, authenticated;

-- Favor is cumulative standing. Promotion checks the threshold but does not spend it.
create or replace function public.promote_character_staff(
  p_character_id integer,
  p_note text
)
returns public.characters
language plpgsql
security definer
set search_path = public
as $$
declare
  character_row public.characters;
  requirement_row public.rank_requirements;
  occupied_slots integer;
  old_position text;
begin
  if not public.is_active_staff() then raise exception 'Staff access required'; end if;
  if nullif(btrim(p_note), '') is null then raise exception 'Note is required'; end if;
  select * into character_row from public.characters where id = p_character_id for update;
  if not found then raise exception 'Character not found'; end if;
  if character_row.promotion_locked then raise exception 'Normal promotion is locked'; end if;
  select * into requirement_row from public.rank_requirements
    where current_position = character_row.position order by id limit 1;
  if not found then raise exception 'No higher rank available'; end if;
  if coalesce(character_row.favor, 0) < requirement_row.favor_required then
    raise exception 'Insufficient favor';
  end if;
  if requirement_row.max_slots is not null then
    select count(*) into occupied_slots from public.characters
    where position = requirement_row.next_position and id <> p_character_id;
    if occupied_slots >= requirement_row.max_slots then raise exception 'Rank slots are full'; end if;
  end if;
  old_position := character_row.position;
  update public.characters set position = requirement_row.next_position
    where id = p_character_id returning * into character_row;
  insert into public.character_history (character_id, action, value, type)
  values (
    p_character_id, 'เลื่อนขั้นโดยสต๊าฟ · ' || btrim(p_note),
    old_position || ' → ' || requirement_row.next_position ||
      ' · ผ่านเกณฑ์ ' || requirement_row.favor_required || ' โปรดปราน',
    'promotion'
  );
  return character_row;
end;
$$;

create or replace function public.promote_character_player(
  p_character_id integer
)
returns public.characters
language plpgsql
security definer
set search_path = public
as $$
declare
  character_row public.characters;
  requirement_row public.rank_requirements;
  occupied_slots integer;
  old_position text;
begin
  select * into character_row from public.characters where id = p_character_id for update;
  if not found then raise exception 'Character not found'; end if;
  if character_row.promotion_locked then raise exception 'Normal promotion is locked'; end if;
  select * into requirement_row from public.rank_requirements
    where current_position = character_row.position order by id limit 1;
  if not found then raise exception 'No higher rank available'; end if;
  if coalesce(character_row.favor, 0) < requirement_row.favor_required then
    raise exception 'Insufficient favor';
  end if;
  if requirement_row.max_slots is not null then
    select count(*) into occupied_slots from public.characters
    where position = requirement_row.next_position and id <> p_character_id;
    if occupied_slots >= requirement_row.max_slots then raise exception 'Rank slots are full'; end if;
  end if;
  old_position := character_row.position;
  update public.characters set position = requirement_row.next_position
    where id = p_character_id returning * into character_row;
  insert into public.character_history (character_id, action, value, type)
  values (
    p_character_id, 'เลื่อนขั้น',
    old_position || ' → ' || requirement_row.next_position ||
      ' · ผ่านเกณฑ์ ' || requirement_row.favor_required || ' โปรดปราน',
    'promotion'
  );
  return character_row;
end;
$$;

revoke all on function public.promote_character_staff(integer, text) from public;
revoke all on function public.promote_character_player(integer) from public;
grant execute on function public.promote_character_staff(integer, text) to authenticated;
grant execute on function public.promote_character_player(integer) to anon, authenticated;

commit;
