create table if not exists public.follower_explorations (
  id bigint generated by default as identity primary key,
  follower_id bigint not null references public.follower_master(id) on delete restrict,
  character_id integer not null references public.characters(id) on delete restrict,
  destination text not null,
  objective text,
  skill_type text,
  skill_value integer,
  status text not null default 'exploring'
    check (status in ('exploring', 'completed', 'cancelled')),
  result_summary text,
  result_details text,
  reward_item_id bigint references public.items(id) on delete set null,
  reward_quantity integer not null default 0 check (reward_quantity >= 0),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  resolved_by uuid references auth.users(id) on delete set null
);

create index if not exists follower_explorations_character_started
  on public.follower_explorations (character_id, started_at desc);

create index if not exists follower_explorations_status_started
  on public.follower_explorations (status, started_at);

create unique index if not exists follower_explorations_one_active_mission
  on public.follower_explorations (follower_id)
  where status = 'exploring';

alter table public.follower_explorations enable row level security;

drop policy if exists "Staff can view follower explorations"
  on public.follower_explorations;
create policy "Staff can view follower explorations"
  on public.follower_explorations for select
  to authenticated
  using (public.is_active_staff());

create or replace function public.start_follower_exploration(
  p_character_id integer,
  p_follower_id bigint,
  p_destination text,
  p_objective text default null
)
returns public.follower_explorations
language plpgsql
security definer
set search_path = public
as $$
declare
  follower_row public.follower_master;
  mission_row public.follower_explorations;
  mission_count integer;
begin
  if nullif(trim(p_destination), '') is null then
    raise exception 'Destination is required';
  end if;

  select * into follower_row
  from public.follower_master
  where id = p_follower_id
  for update;

  if not found
    or follower_row.owner_character_id is distinct from p_character_id then
    raise exception 'Follower does not belong to this character';
  end if;

  if btrim(coalesce(follower_row.status, ''), E' \n\r\t') <> 'idle' then
    raise exception 'Follower is already on a mission';
  end if;

  select count(*) into mission_count
  from public.follower_explorations
  where follower_id = p_follower_id
    and started_at >= date_trunc('week', now())
    and status <> 'cancelled';

  if mission_count >= coalesce(follower_row.weekly_mission_limit, 1) then
    raise exception 'Follower weekly mission limit reached';
  end if;

  insert into public.follower_explorations (
    follower_id,
    character_id,
    destination,
    objective,
    skill_type,
    skill_value
  )
  values (
    p_follower_id,
    p_character_id,
    trim(p_destination),
    nullif(trim(p_objective), ''),
    follower_row.skill_type,
    follower_row.skill_value
  )
  returning * into mission_row;

  update public.follower_master
  set status = 'exploring', updated_at = now()
  where id = p_follower_id;

  insert into public.character_history (
    character_id,
    action,
    value,
    type
  )
  values (
    p_character_id,
    'ส่งผู้ติดตามสำรวจ',
    follower_row.name || ' → ' || trim(p_destination),
    'follower_mission'
  );

  return mission_row;
end;
$$;

create or replace function public.get_player_follower_explorations(
  p_character_id integer
)
returns table (
  id bigint,
  follower_id bigint,
  destination text,
  objective text,
  status text,
  result_summary text,
  result_details text,
  reward_item_name text,
  reward_quantity integer,
  started_at timestamptz,
  completed_at timestamptz
)
language sql
security definer
set search_path = public
stable
as $$
  select
    mission.id,
    mission.follower_id,
    mission.destination,
    mission.objective,
    mission.status,
    mission.result_summary,
    mission.result_details,
    reward.name,
    mission.reward_quantity,
    mission.started_at,
    mission.completed_at
  from public.follower_explorations mission
  left join public.items reward on reward.id = mission.reward_item_id
  where mission.character_id = p_character_id
  order by mission.started_at desc
  limit 30;
$$;

create or replace function public.resolve_follower_exploration(
  p_mission_id bigint,
  p_result_summary text,
  p_result_details text default null,
  p_reward_item_id bigint default null,
  p_reward_quantity integer default 0
)
returns public.follower_explorations
language plpgsql
security definer
set search_path = public
as $$
declare
  mission_row public.follower_explorations;
  follower_row public.follower_master;
  reward_item public.items;
  reward_text text := '';
begin
  if not public.is_active_staff() then
    raise exception 'Staff access required';
  end if;

  if nullif(trim(p_result_summary), '') is null then
    raise exception 'Result summary is required';
  end if;

  if p_reward_quantity < 0
    or (p_reward_item_id is null and p_reward_quantity > 0)
    or (p_reward_item_id is not null and p_reward_quantity <= 0) then
    raise exception 'Invalid reward quantity';
  end if;

  select * into mission_row
  from public.follower_explorations
  where id = p_mission_id
  for update;

  if not found or mission_row.status <> 'exploring' then
    raise exception 'Active exploration not found';
  end if;

  select * into follower_row
  from public.follower_master
  where id = mission_row.follower_id
  for update;

  if p_reward_item_id is not null then
    select * into reward_item
    from public.items
    where id = p_reward_item_id and active
    for update;

    if not found then
      raise exception 'Active reward item not found';
    end if;

    if reward_item.is_limited then
      if reward_item.stock_quantity < p_reward_quantity then
        raise exception 'Insufficient reward stock';
      end if;

      update public.items
      set
        stock_quantity = stock_quantity - p_reward_quantity,
        updated_at = now()
      where id = reward_item.id;
    end if;

    insert into public.character_inventory (
      character_id,
      item_name,
      quantity
    )
    values (
      mission_row.character_id,
      reward_item.name,
      p_reward_quantity
    )
    on conflict (character_id, item_name)
    do update set quantity =
      public.character_inventory.quantity + excluded.quantity;

    insert into public.inventory_transactions (
      item_id,
      character_id,
      quantity_change,
      transaction_type,
      note,
      created_by
    )
    values (
      reward_item.id,
      mission_row.character_id,
      -p_reward_quantity,
      'grant',
      'รางวัลจากภารกิจผู้ติดตาม: ' || trim(p_result_summary),
      auth.uid()
    );

    reward_text := ' · ได้รับ ' || reward_item.name ||
      ' ×' || p_reward_quantity;
  end if;

  update public.follower_explorations
  set
    status = 'completed',
    result_summary = trim(p_result_summary),
    result_details = nullif(trim(p_result_details), ''),
    reward_item_id = p_reward_item_id,
    reward_quantity = p_reward_quantity,
    completed_at = now(),
    resolved_by = auth.uid()
  where id = p_mission_id
  returning * into mission_row;

  update public.follower_master
  set status = 'idle', updated_at = now()
  where id = mission_row.follower_id;

  insert into public.character_history (
    character_id,
    action,
    value,
    type
  )
  values (
    mission_row.character_id,
    follower_row.name || ' กลับจากสำรวจ',
    trim(p_result_summary) || reward_text,
    'follower_result'
  );

  return mission_row;
end;
$$;

create or replace function public.cancel_follower_exploration(
  p_mission_id bigint,
  p_reason text default null
)
returns public.follower_explorations
language plpgsql
security definer
set search_path = public
as $$
declare
  mission_row public.follower_explorations;
begin
  if not public.is_active_staff() then
    raise exception 'Staff access required';
  end if;

  update public.follower_explorations
  set
    status = 'cancelled',
    result_summary = coalesce(nullif(trim(p_reason), ''), 'ยกเลิกภารกิจ'),
    completed_at = now(),
    resolved_by = auth.uid()
  where id = p_mission_id
    and status = 'exploring'
  returning * into mission_row;

  if not found then
    raise exception 'Active exploration not found';
  end if;

  update public.follower_master
  set status = 'idle', updated_at = now()
  where id = mission_row.follower_id;

  return mission_row;
end;
$$;

revoke all on function public.start_follower_exploration(
  integer, bigint, text, text
) from public;
revoke all on function public.get_player_follower_explorations(integer)
  from public;
revoke all on function public.resolve_follower_exploration(
  bigint, text, text, bigint, integer
) from public;
revoke all on function public.cancel_follower_exploration(bigint, text)
  from public;

grant execute on function public.start_follower_exploration(
  integer, bigint, text, text
) to anon, authenticated;
grant execute on function public.get_player_follower_explorations(integer)
  to anon, authenticated;
grant execute on function public.resolve_follower_exploration(
  bigint, text, text, bigint, integer
) to authenticated;
grant execute on function public.cancel_follower_exploration(bigint, text)
  to authenticated;

